### ISSUE TITLE
(Charlas cortas) La hora de la herramienta con AsturiasHacking 2

### ISSUE THREAD

**Issue by m1guelpf** [asturiashacking/activities#10]
# Propuesta de Actividad

## Título

La hora de la herramienta con AsturiasHacking (segunda tanda)

## Descripción

Tras el primer evento de la hora de la herramienta (#8), quedaron algúnas actividades propuestas de personas que no pudieron asistir o herramientas que se propusieron en el último momento, por lo que me parece que sería bueno hacer una segunda edición.

## Nivel

Cualquiera que utilice un ordenador a diario podría aprender de las charlas cortas, aunque la idea es que se centren en herramientas relacionadas con la programación.

## Información adicional

Si vas a hablarnos sobre alguna herramienta, sería bueno que trajeras un ordenador con conexión HDMI o algún adaptador para el proyector.

Si solo vienes a escuchar, no hace falta que traigas nada :)

## Sobre mí

No aplica, las charlas las dará toda persona que quiera :)

## Herramientas

| Herramienta | Ponente |
| -------------------- | ------------- |
| Visual Studio Code | @m1guelpf |
| [QtCreator](https://www.qt.io/qt-features-libraries-apis-tools-and-ide/#ide) | @jsfdez |
| AWM | @jsfdez |
| Gerrit + GIT | @jsfdez |
| [Portainer](https://github.com/portainer/portainer) | @iquesada |
| [Sentry](https://sentry.io) | @Jonatanmdez |
| ag | @dgsuarez |
| jq | @dgsuarez |
| csvkit | @dgsuarez |
| Fiddler | @morvader |

**Comment by iquesada** [comment]
Yo estoy trasteando con [Portainer](https://github.com/portainer/portainer), un UI para Docker y podría contar algo sobre él ¿Os parece interesante?

**Comment by Jonatanmdez** [comment]
Yo vuelvo a proponer si os parece Sentry. Creo que es muy util y una gran desconocida .

Y se puede explicar en 10 minutos sin problemas :)

**Comment by sergioalvz** [comment]
¡Muchas gracias por crear la actividad @m1guelpf! Tenemos que ir buscándole un encaje para los próximos meses.

**Comment by tasugo** [comment]
Otras que quedaron pendientes del otro hilo, añádelas si quieres, @m1guelpf:

ag - @dgsuarez
jk - @dgsuarez
csvkit - @dgsuarez
Gerrit + Git - @jsfdez
Fiddler - @morvader

:)

**Comment by iquesada** [comment]
Creo que ya se vislumbra una tercera sesión ;)

**Comment by m1guelpf** [comment]
@tasugo Añadidas, gracias

**Comment by dgsuarez** [comment]
Contad conmigo para hablar de esas (u otras! acepto sugerencias). Por cierto que hay un typo, es jq, no jk :p

**Comment by tasugo** [comment]
Es hora de rescatar esta charla para la actividad de marzo! (que tiene pinta de que nos pillará a principios de abril, porque en semana santa cierran nuestras sedes habituales xD).

Cómo lo veríais para el jueves día 5?

ping @morvader @jsfdez @dgsuarez @m1guelpf @Jonatanmdez @iquesada

Y quie quiera animarse, estamos a tiempo! :)

**Comment by iquesada** [comment]
Por mi perfecto!

El 20 mar. 2018 6:47 p. m., "Manuel Gómez" <notifications@github.com>
escribió:

Es hora de rescatar esta charla para la actividad de marzo! (que tiene
pinta de que nos pillará a principios de abril, porque en semana santa
cierran nuestras sedes habituales xD).

Cómo lo veríais para el jueves día 5?

ping @morvader <https://github.com/morvader> @jsfdez
<https://github.com/jsfdez> @dgsuarez <https://github.com/dgsuarez>
@m1guelpf <https://github.com/m1guelpf> @Jonatanmdez
<https://github.com/jonatanmdez> @iquesada <https://github.com/iquesada>

Y quie quiera animarse, estamos a tiempo! :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/asturiashacking/activities/issues/10#issuecomment-374693013>,
or mute the thread

**Comment by jsfdez** [comment]
Yo estaré en Gijón desde el día 22 hasta el 30 de abril.

**Comment by Jonatanmdez** [comment]
Sin problemas por mi parte

**Comment by dgsuarez** [comment]
:+1:

**Comment by morvader** [comment]
Buenas,

Yo aún no sé si ese día podré asistir o no. Si finalmente voy ningún problema en presentaros la herremienta.

**Comment by sergioalvz** [comment]
Acabamos de publicar y anunciar el evento: https://www.meetup.com/AsturiasHacking/events/249095656/

Finalmente: jueves día 5 de abril 2018 🎉

**Comment by dgsuarez** [comment]
@sergioalvz @tasugo una cosilla, aunque sean 3 herramientas diferentes son muy sencillitas, yo creo que en 15 minutos lo ventilo, o puedo extenderlo un poco para ver como combinarlas con otras utilidades, lo que os cuadre más :slightly_smiling_face:

**Comment by sergioalvz** [comment]
De cara a ir organizando la actividad para esta semana, @dgsuarez @iquesada @Jonatanmdez han confirmado que pueden acudir sin problemas. Estamos a la espera de @morvader @m1guelpf y @jsfdez para cerrar la agenda.

**Comment by morvader** [comment]
Finalmente no creo que pueda asistir este jueves :( . Lo dejo para la siguiente

Perdonad las molestinas

**Comment by sergioalvz** [comment]
Thanks por avisar, Fran. Te esperamos en la próxima! :)

**Comment by m1guelpf** [comment]
Yo tampoco voy a poder asistir, lo siento

**Comment by sergioalvz** [comment]
Puedo coger el testigo de los compañeros que no pueden acudir y hablar de un nuevo «bundler» de JavaScript que promete 0 configuración y un resultado similar al resto de alternativas.

**Comment by iquesada** [comment]
Yo puedo hablar de teamocil (https://github.com/remiprev/teamocil). Es una herramienta sencilla, lo ventilo en dos minutos.

**Comment by tasugo** [comment]
Y yo puedo hablar de Glitch.com, que es un proyecto que me tiene mosca (en el buen sentido) desde hace tiempo :)

**Comment by sergioalvz** [comment]
Resumen de la agenda a día de hoy con las altas y bajas de última hora:

| Herramienta | Ponente | 
| ------------  | --------- |
| [Portainer](https://github.com/portainer/portainer) | @iquesada |
| [Teamocil](https://github.com/remiprev/teamocil) | @iquesada |
| [Sentry](https://sentry.io) | @Jonatanmdez |
| ag | @dgsuarez |
| jq | @dgsuarez |
| csvkit | @dgsuarez |
| ParcelJS | @sergioalvz |
| Glitch | @tasugo |

Se ruega confirmación :) Podría haber hueco para 1-2 charlas más.

**Comment by tasugo** [comment]
Confirmo! :D

**Comment by jmrp81** [comment]
Buenas chicxs,

He visto se ha caído la de Visual Studio Code, tampoco quiero pisar la charla de @m1guelpf pero si os apatece puedo darla yo de Visual Studio Code, si la de Miguel iba orientada más al editor en general yo la puedo orientar hacia las extensiones.

Saludos

**Comment by azaharafernandezguizan** [comment]
Hola, y si os queda hueco y lo véis adecuado yo puedo hablar de Visual Studio + TFS orientado a .Net, para aquellos que no lo conozcan para mostrar porque el idle es muy querido por los desarrolladores .Net.

**Comment by iquesada** [comment]
Confirmo ;)

**Comment by sergioalvz** [comment]
Actualización con las últimas propuestas de @azaharafernandezguizan y @jmrp81 !

**QUEDA COMPLETA LA AGENDA PARA ESTA SESIÓN**

| Herramienta | Ponente | 
| ------------  | --------- |
| [Portainer](https://github.com/portainer/portainer) | @iquesada |
| [Teamocil](https://github.com/remiprev/teamocil) | @iquesada |
| [Sentry](https://sentry.io) | @Jonatanmdez |
| ag | @dgsuarez |
| jq | @dgsuarez |
| csvkit | @dgsuarez |
| ParcelJS | @sergioalvz |
| Glitch | @tasugo |
| Visual Studio Code | @jmrp81 |
| Visual Studio + TFS | @azaharafernandezguizan |

**Comment by dgsuarez** [comment]
presente! :raising_hand_man:

**Comment by Jonatanmdez** [comment]
Confirmo 👋
