### ISSUE TITLE
Nueva propuesta: mesa redonda sobre reconvertidos a las TICs

### ISSUE THREAD

**Issue by azaharafernandezguizan** [asturiashacking/activities#11]
**# Propuesta de Actividad**

**Título**

Reconvertidos a las TIC, por qué y ventajas/desventajas con otros sectores.

**Descripción**

En este sector muchos de los nuevos profesionales son personas que previamente habían estudiado otra rama o incluso habían trabajado en otros puestos de trabajo alejados del sector tecnológico. Muchos de estos profesionales, un día decidieron reorientarse, entre los que me incluyo y cambiar de sector. 
Propongo una mesa redonda, en la que cada ponente resumirá en no más de cinco o diez minutos su historia previa y como llegó a trabajar en las TICs. Posteriormente se comenzará con el debate, en el que se irán respondiendo preguntas o abordando temas que propongan las personas asistentes.

**Nivel**

Entiendo la actividad como algo positivo, siempre una comparativa evitando negatividades y obteniendo de ello las diferentes visiones que aportan personas con diferentes experiencias.
Creo que podría ser una charla abierta a la comunidad, pero también incluso a aquellas personas que les pueda interesar porque estén pensando si reorientarse.

**Información adicional**

Necesitamos personas que quieran participar como ponentes en la mesa redonda, y luego dependiendo del aforo, el lugar puede ser más o menos grande. Admite desde una mesa redonda mientras nos tomamos algo, hasta un evento ya más formal.

**Sobre mí**

Yo me propongo como participantes de la mesa redonda, soy Doctora en Inmunología (sector que abandoné) y desarrolladora de software (sector en el que me encuentro más cómoda). Os resumiré por qué elegí la ciencia y un poco mi periplo hasta acabar programando, que por cierto es algo que me apasiona.

**Comment by Jonatanmdez** [comment]
Tiene muy buena pinta la verdad.

**Comment by sergioalvz** [comment]
@azaharafernandezguizan qué te parece el día 22 de febrero como fecha para el evento?

cc: @tasugo

**Comment by azaharafernandezguizan** [comment]
Hola,

Por mi perfecto!

Saludos
