### ISSUE TITLE
Nueva propuesta: OpenSource Build & Deployment System para OpenShift & Kubernetes

### ISSUE THREAD

**Issue by igayoso** [asturiashacking/activities#13]
# Propuesta de Actividad

## Título

OpenSource Build & Deployment System para OpenShift & Kubernetes

## Descripción

Usando docker para desarrollar en entornos locales, muchas veces nos encontramos que no sabemos como replicar este entorno de una forma fácil en producción. Otro de los problemas que nos encontramos a la hora de hacer testing de nuestro código es que es muy complicado tener varios entornos, lo mas fieles a producción, para probar nuevas ramas o Pull Requests. lagoon nos ayudara con todos estos "problemas" y podremos focalizarnos en desarrollar de forma local y asegurándonos que llegue a producción de una forma fácil y segura.

Más info en el Github de [lagoon](https://github.com/amazeeio/lagoon)

## Nivel

En la charla nos centraremos en enseñar como funciona el proyecto lagoon de una forma muy global, por lo tanto no se necesita conocimiento previo alguno, quizá unas nociones básicas sobre docker y pipelines de Continuous Integration/Deployment.

## Información adicional

Con una pantalla/proyector para los asistentes y un sitio con conexión a Internet o cobertura móvil seria suficiente.

## Sobre mí

Me llamo [Israel](http://igayoso.net), asturiano afincado en Barcelona y trabajando para [amazee.io](https://amazee.io), empresa que esta implementando lagoon a sus clientes y que esta detrás del proyecto OpenSource. Me gustaría enseñar públicamente el proyecto, que aunque este en una version en desarrollo (pero ready for production) podría ser de gran ayuda a otras empresas que quieran implementarlo o incluso usar el servicio de amazee.io.

Mi experiencia profesional es amplia en el mundo de sistemas Linux y en los últimos años trabajando casi íntegramente con docker y kubernetes en diferentes empresas y clientes. También tengo experiencia tanto en entornos cloud (AWS, GCloud...) como en hardware físico.

**Comment by sergioalvz** [comment]
¡Qué buena pinta @igayoso! Gracias por la propuesta 🙂

¿Tienes alguna fecha en la cabeza para poder impartirla? 

Un saludo!

**Comment by Jonatanmdez** [comment]
Me parece super interesante. Cada vez más se usa no solo docker para testing sino para producción. 

Es la mejor manera ademas de estar seguro al 100% de que todo funciona, cuando literalmente la misma imagen de docker se usa para el test y luego se pública en producción

**Comment by tasugo** [comment]
Ufff... Yo estoy intentando coscarme de Kubernetes pero de momento me supera. Esto me suena a música celestial xD

**Comment by morvader** [comment]
Genial propuesta!. La verdad que suena super interesante

**Comment by igayoso** [comment]
Me encanta de que os parezca interesante mi propuesta 😄. Sobre fechas, tengo programado que estare por Asturias la semana del 26 de Marzo y luego ya creo que hasta la semana del 30 de Abril no vuelva a estar por alli. No se como os vendrian esas fechas, pero si no, podemos ir viendolo que no creo que haya mayor problema...

**Comment by sergioalvz** [comment]
@igayoso en principio nos está encajando mejor para Abril. Esa semana del 30 pinta bien :)

**Comment by igayoso** [comment]
@sergioalvz perfecto, no hay problema :) En teoria, estare alli la semana del 30 de Abril... Ya me direis si necesitais algo o lo que sea :)

**Comment by tasugo** [comment]
Ponemos como fecha tentativa el 3 de mayo? :)

**Comment by igayoso** [comment]
Por mi parte perfecto!!

**Comment by iquesada** [comment]
Tiene una pinta brutal, yo no me la pierdo!

**Comment by azaharafernandezguizan** [comment]
Ya tengo ganas de acudir! Tiene una pinta fenomenal

**Comment by isaacguerrateijeiro** [comment]
Que genial la propuesta! No me la pierdo!

**Comment by sergioalvz** [comment]
@igayoso te dejo por aquí la descripción del Meetup! Como comentó Manu, partimos con el día 3 de mayo como fecha: https://www.meetup.com/AsturiasHacking/events/249097148/ si ves que alguna cosa no te encaja o encuentras algo en la descripción que se podría mejorar, avísame sin problema, please! 🙂

**Comment by igayoso** [comment]
Ya lo he visto y me parece genial. En teoria estare por aqui por esas fechas asi que todo perfecto. Muchas gracias por organizarlo todo!

**Comment by sergioalvz** [comment]
Hola @igayoso, ya hemos confirmado el espacio; nos han cedido el salón de conferencias del Edificio IMPULSA en el Parque Tecnológico! Si necesitas que te acerquemos o lo que sea, avísanos sin problema :)

Está toda la información actualizada en Meetup: https://www.meetup.com/AsturiasHacking/events/249097148/

En breves empezamos a darle promoción a tope 🎉

**Comment by igayoso** [comment]
Yeah! Que sitio mas chulo, no lo conocia. En teoria tendre forma de llegar, pero si tengo algun problema o algo os avisare para acoplarme con alguno de vosotros, gracias!!!

Gracias por la promo, si necesitais alguna cosa por mi parte, no dudeis en decirmelo :)

**Comment by sergioalvz** [comment]
Hola @igayoso, se me olvidó comentarte que, por lo general, intentamos que la duración de la charla no sobrepase los 50 minutos - 1 hora (más un tiempo de preguntas después). ¿Te encaja? 

En principio, tenemos la sala disponible durante una hora y media.

Un saludo!

**Comment by igayoso** [comment]
@sergioalvz no habra problema (espero). Mi idea era hacer unos 30 minutos de charla y unos 15 minutos de demo para mostrar como funciona y para finalizar dar tiempo para las preguntas.

Saludos!
