### ISSUE TITLE
Lenguajes de programación modernos: lambdas, futures y metaprogramación

### ISSUE THREAD

**Issue by jcaicoya** [asturiashacking/activities#18]
# Propuesta de Actividad

## Título
Lenguajes de programación modernos: lambdas, futures y metaprogramación

## Descripción

En el año 2011 se aprobó el nuevo estándar de C++ (el anterior era del 2003), y se alcanzó el compromiso de aprobar revisiones cada tres años, de ahí que tengamos las versiones 2014, la reciente 2017 y la próxima para el 2020. Estamos intentando dotar al lenguaje de algunas de las capacidades que tienen otros lenguajes más modernos, sin perder la esencia y las ventajas del C++.
He escogido tres de las mejoras más destacadas para realizar una aproximación conceptual a qué son y cómo pueden usarse:
lambdas: qué son, cómo se aplican a la programación funcional, ejemplos, mónadas
futures: qué son, diferencias y similitudes entre multithreading, futures y parallelism
metaprogramación: uso de plantillas, capacidades y limitaciones

## Nivel

Nivel básico: es una introducción a estas técnicas de programación.

## Información adicional

La idea es comentar las técnicas (con algún ejemplo práctico), y dialogar sobre su utilidad actual y posible. En el Comité, nos interesa saber si lo que hacemos está teniendo o puede tener aplicación real.

## Sobre mí

Soy Jose Caicoya, matemático y desarrollador C++, y formo parte del Comité de Estandarización de C++ (https://isocpp.org/std/the-committee).
Me encanta programar, me dedico a ello profesionalmente, y me encanta compartir, asisto a todas las charlas que puedo y las he dado aquí en el PCTG, para la Universidad, y en Carlos III en el evento using std cpp.

**Comment by sergioalvz** [comment]
Esta me parece súper interesante @jcaicoya, gracias por todas las propuestas!

**Comment by jcaicoya** [comment]
Buenos días. Reaprovechando parte del contenido que tengo de otras charlas, describo un poco más los puntos.
1. Lambdas: Definición, ejemplos de uso. Paradigma de programación funcional. Aplicación en lenguajes declarativos. Mónadas.
2. Futures: Distinción entre programación en paralelo, multihilo y uso de futures. Ejemplo de aplicación de cada una de ellas. Pruebas. Inclusión en el lenguaje.
3. Metaprogramación: La charla de Diego Guerra fue excelente; comentaría el uso de plantillas (templates) como introducción a las restricciones (constraints) y conceptos. Este punto puede que sea "demasiado C++"), y habida cuenta que los otros dos pueden dar mucho de sí, tal vez sea mejor no incluirlo.
¿Qué te parece?

**Comment by sergioalvz** [comment]
Contundente, Jose, pero muy interesante :) Intentamos buscarle hueco asap.

**Comment by jcaicoya** [comment]
Estupendo. Voy preparando, para cuando llegue el momento. :)

**Comment by sergioalvz** [comment]
Hola Jose, no acostumbramos a cerrar una issue hasta que la actividad se haya realizado. Vuelvo a abrirlo hasta entonces 😉

**Comment by jcaicoya** [comment]
Hola Sergio; perdona, soy un desastre, me lié con nuestro Jira, creí que cerraba el comentario y volvía a la página anterior, no que estaba cerrando la issue.
Disculpa la molestia.

Saludos,
Jose Caicoya

**Comment by tasugo** [comment]
@jcaicoya estamos manejando el 19 de abril como fecha tentativa para esta charla. A ti te encajaría? :)

**Comment by jcaicoya** [comment]
Buenas; justo el jueves 19 y el viernes 20 tengo reunión en Madrid del G22 (grupo de trabajo de estandarización de lenguajes de programación; solo está propuesta, no confirmada, pero raro será que se modifique.
Cuento con ir a Madrid la tarde del miércoles 18; ¿os viene bien hacerla el martes 17, o ya la siguiente semana, el día que prefiráis?

**Comment by tasugo** [comment]
En principio ningún problema con hacerla de martes. Te confirmamos esta semana próxima :)

**Comment by sergioalvz** [comment]
Hola @jcaicoya, de cara a describir el evento en Meetup, entiendo que en esta charla, aunque puedas utilizar `C++` para ejemplificar algunos conceptos, no vas a ahondar en el lenguaje si no en los conceptos y programación funcional, ¿verdad?

**Comment by jcaicoya** [comment]
Sí, eso es.
La idea parte de ¿porqué hemos introducido en C++ estas capacidades? ¿Qué nos puede aportar?. Por más queramos, tenemos limitaciones que nos impiden conseguir lo que otros lenguajes tienen de manera natural.
Lo que sí que me parece interesante es incorporar técnicas a nuestra capacidad como programadores, saber que existen y tal vez, usarlas. O, como es mi caso, adaptarlas a la manera en que pienso una solución.
Que sea o no en C++, no es relevante. Para mí es más natural, pero las ideas, en este caso, deben estar por encima del lenguaje.
Sí me gustaría poder “vender” el C++ moderno, de ahí las otras propuestas. Pero no aquí.
También me quiero aprovechar de vuestra experiencia y conocimiento: cualquier sugerencia será bienvenida. 🙂

**Comment by sergioalvz** [comment]
@jcaicoya te dejo por aquí un borrador con la descripción de la actividad: https://www.meetup.com/AsturiasHacking/events/249101826/

Please, avísame si ves algo que no te encaje o que se pueda mejorar :) Como ves, de momento figura la propuesta de fecha de Manu del martes 17 de abril.

**Comment by jcaicoya** [comment]
Buenas; está muy bien, pero siento tener que desdecirme con la fecha: ¿la podemos cambiar para la siguiente semana (da igual el día)?. Tengo que adelantar el viaje a Madrid de esa semana. Aún no lo he hecho, por si no pudiésemos cambiar esta fecha, que me obligaría a irme para Madrid el mismo martes justo al acabar la charla.
Espero a que me contestéis.

**Comment by sergioalvz** [comment]
@jcaicoya ¿confirmamos que te va bien la fecha? 🙂

**Comment by jcaicoya** [comment]
Sí, sí: ya vi que reservasteis el Antiguo Instituto, así que busqué avión para el día siguiente tempranico, y ya lo tengo.
¡Sin problema, muchas gracias!

Saludos,
Jose Caicoya

**Comment by sergioalvz** [comment]
Hola,

dejo por aquí las transparencias de la charla de @jcaicoya. Muchas gracias de nuevo por la ponencia, ¡muy amena y divertida! 😃 

[Lenguajes de programación modernos_ lambdas, futures y metaprogramación.pdf](https://github.com/asturiashacking/activities/files/1931775/Lenguajes.de.programacion.modernos_.lambdas.futures.y.metaprogramacion.pdf)

Un saludo!
