### ISSUE TITLE
Modern C++: repaso a las principales novedades introducidas en C++11, 14 y 17

### ISSUE THREAD

**Issue by jcaicoya** [asturiashacking/activities#19]
# Propuesta de Actividad

## Título
Modern C++: repaso a las principales novedades introducidas en C++11, 14 y 17

## Descripción

Repasaremos algunas de las principales novedades introducidas en los nuevos estándares de C++:
move semantics
variadic templates
smart pointers
return type deduction
std::variant
std::any
std::optional
std::string_view

## Nivel

Básico, ya que se tratará de una introducción, una explicación de los conceptos sin entrar en detalle, en implementaciones complejas. La idea es cualquier programador, trabaje en el lenguaje que sea, valore estas mejoras como parte de su arsenal.

## Información adicional

En principio es una exposición de temas, aunque se ruega participación. Si alguien quiere, puede ponerse en contacto con nosotros para que le indiquemos qué compilador puede usar según el SO que elija para poder cacharrear. En cualquier caso, hay compiladores online que podremos usar.

## Sobre mí

Soy Jose Caicoya, matemático y desarrollador C++, y formo parte del Comité de Estandarización de C++ (https://isocpp.org/std/the-committee).
Me encanta programar, me dedico a ello profesionalmente, y me encanta compartir, asisto a todas las charlas que puedo y las he dado aquí en el PCTG, para la Universidad, y en Carlos III en el evento using std cpp.

**Comment by sergioalvz** [comment]
Cierro este issue por ir de manera conjunta con #20 😃
