### ISSUE TITLE
Modern C++: ¿qué podría ser C++20? Corrutinas, conceptos, paralelismo, reflexión...

### ISSUE THREAD

**Issue by jcaicoya** [asturiashacking/activities#20]
# Propuesta de Actividad

## Título

Modern C++: ¿qué podría ser C++20? Corutinas, conceptos, paralelismo, reflexión...

## Descripción

En 2020 se aprobará una nueva revisión del Estándar C++, en el que se incluirán nuevas y poderosas capacidades (esperamos conseguir una mayor version), algunas de las cuales ya están aprobadas. Hablaremos de:
-Corrutinas
-Conceptos
-Paralelismo
-Reflexión
-Paquetes
-Rangos

## Nivel

Nivel básico: hablaremos sobre lo que se pretende, captando ideas de otros lenguajes

## Información adicional

Aún no hay estándar, así que lo único que tenemos son implementaciones de prueba para algún compilador. Podemos comparar con el uso en otros lenguajes, como ejemplo tenemos la reflexión.

## Sobre mí

Soy Jose Caicoya, matemático y desarrollador C++, y formo parte del Comité de Estandarización de C++ (https://isocpp.org/std/the-committee).
Me encanta programar, me dedico a ello profesionalmente, y me encanta compartir, asisto a todas las charlas que puedo y las he dado aquí en el PCTG, para la Universidad, y en Carlos III en el evento using std cpp.

**Comment by tasugo** [comment]
Me gustan tanto esta como #19, pero no podrían quizá fusionarse en una sola? Lo digo por no saturar de contenido de una sola tecnología (en este caso C++) el roadmap de charlas de los próximos meetups. Si no lo ves claro y te molaría dar las dos en profundidad, sin compromiso, ojo. Buscamos acomodo :)

**Comment by jcaicoya** [comment]
Hola; pues realmente sí que se pueden fusionar: quizás sea interesante el hacerlo así: contar las novedades de los últimos años, y una breve descripción de lo que pretendemos llevar para el 2020. Sobre todo para que pueda sear interesante para más personas, no solo para programadores que estén desarrollando en C++. La preparo de esta manera, y si tras el meetup vemos que hay interés en profundizar, lo preparamos. )

**Comment by sergioalvz** [comment]
Hola @jcaicoya ! ¿Qué tal? Si quieres, podemos buscar hueco para esta charla siguiendo la recomendación de @tasugo de fusionarla con #19. Por ejemplo, ¿qué tal marzo?

Un saludo!

**Comment by jcaicoya** [comment]
¡Hola @sergioalv!
Todo bien, sobre todo por estar de vacaciones, y aún me queda una semana.
El 7 de marzo voy al using::std cpp, en Madrid, he presentado una charla, aún no sé si me la cogerán. Si es así, podría presentar aquí un mix de la #19 y la #20: buscaré algo que pueda ser interesante fuera del ámbito (estricto) de C++.  Me vendría bien a finales de mes, para tener más tiempo para prepárala (lo que tengo, es solo para “vender” C++ moderno a gente de C++).
¿Te parece bien?

**Comment by sergioalvz** [comment]
@jcaicoya Me parece perfecto! ¿Qué tal el día 28 de marzo?

**Comment by jcaicoya** [comment]
Hola @sergioalvz, cuento con ese día.
Ahora mismo estoy a tope con una práctica de la UNED (estoy estudiando Tecnologías de la Información), que espero acabar en pocos días: el plazo es hasta el día 10. En cuanto lo haga, voy a pensar qué puedo mostrar como vehículo conductor de las novedades de C++ (solo tengo claro que los smart pointers y la semántica de movimientos aparecerán), de forma que sea atractivo para programadores de otros lenguajes.
Te voy contando según tenga algo. Se pueden usar compiladores online, para que quien quiera pueda ejecutar el código en caliente. ¡A ver qué se me ocurre!

¡Un abrazo!

**Comment by sergioalvz** [comment]
Genial @jcaicoya, ya está [en el calendario](https://www.meetup.com/AsturiasHacking/events/257856665/). 

Suerte con esas prácticas y demás eventos! :)))

**Comment by sergioalvz** [comment]
@jcaicoya simplemente recordarte que la duración de la charla es, como máximo, de 50 minutos! :)

**Comment by jcaicoya** [comment]
Hola @sergioalvz; gracias por el recordatorio: la del año pasado fue muy larga. Esta vez no será así.
Ahora mismo estoy a tope, no tengo tiempo para discurrir, pero mi idea es conseguir algo interactivo y/o sobre todo de interés fuera del C++: buscar una aplicación que podamos hacer (o destripar) en C++ en una media hora, comentando técnicas.
Yo tengo alguna librería propia de criptografía básica, podría servir. O buscar algo más moderno. A ver qué se me ocurre. Por supuesto, cualquier sugerencia es bienvenida.

**Comment by sergioalvz** [comment]
Done: https://www.meetup.com/AsturiasHacking/events/257856665/ ! Gracias de nuevo :)
