### ISSUE TITLE
Caso práctico: Design-first en el desarrollo de APIs

### ISSUE THREAD

**Issue by sergioalvz** [asturiashacking/activities#21]
# Propuesta de Actividad

## Título

Caso práctico: Design-first en el desarrollo de APIs

## Descripción

No es extraño que, muchas veces, cuando desarrollamos una API REST o cualquier tipo de interfaz, caigamos en la tentación de centrarnos directamente en sus detalles de implementación (¿lo divertido?) antes incluso de hacer un análisis superficial de la funcionalidad que vamos a construir o qué diseño queremos alcanzar. En esta actividad, os propongo un ejercicio diferente: diseñar una API REST antes incluso de escribir ni una sola línea de su lógica de negocio. ¿Conseguiremos replicar aquí los beneficios de otras metodologías como TDD? :)

Para realizar la actividad, me apoyaré en los siguientes conceptos y tecnologías:

* Design-first && Code-first
* Top-down && Bottom-up
* TDD
* REST (o RESTful-like APIs)
* OpenAPI (formerly Swagger)
* Node + TypeScript  

## Nivel

No se necesita ningún conocimiento previo. Quizás saber *grosso modo* qué es una API, aunque en principio debería ser sencillo deducirlo durante el transcurso de la actividad.

## Información adicional

* Proyector y conexión a Internet.

Intentaré hacer un ejercicio de *live coding*, por lo que podéis llevar con vosotrxs ordenador para hacerlo de manera simultánea (no garantizo nada :joy: ).

## Sobre mí

Poco que decir. Llevo organizando este sarao un par de años.

**Comment by LuisM000** [comment]
¡Suena genial!

**Comment by azaharafernandezguizan** [comment]
Una gran idea!!! Esperando ya al meetup

**Comment by jmrp81** [comment]
Me encanta la idea.

**Comment by markinosags** [comment]
Mola! A ver si puedo ir

**Comment by iquesada** [comment]
Me parece una gran propuesta, Sergio. Muy interesante, cuenta conmigo!

**Comment by Jonatanmdez** [comment]
No tengo ni idea que eso del design first... así que alli estare para aprender :)

**Comment by sergioalvz** [comment]
Todo apunta al 17 de mayo para esta: https://www.meetup.com/AsturiasHacking/events/249100549/
