### ISSUE TITLE
Introducción al front mediante "Holas Mundos"

### ISSUE THREAD

**Issue by azaharafernandezguizan** [asturiashacking/activities#22]
# Propuesta de Actividad

## Titulo

Introducción al front mediante "Holas Mundos"

## Descripción

¿Estás pensando en comenzar un proyecto utilizando un framework Javascript? Al inicio, navegar entre toda la información disponible en la web y conocer que hace falta para comenzar a desarrollar con un framework deteerminado puede ser un poco difícil. 

En este meetup lo que pretendemos es introducir algunos de los frameworks Javascript como son: Angular, Aurelia, Angular con Material, NativeScript, Vue, React e Ionic. Para ello contaremos que son, en que se diferencian, que recursos hemos encontrado nosotros que nos han resultado útiles y como son los primeros pasos para configurar el entorno y la arquitectura que crean por defecto.

Será una primera visión global de cómo comenzar a desarrollar un proyecto con alguno de estos frameworks desde el punto de vista de alguien sin experiencia previa en ellos.

## Nivel

Totalmente para principiantes, tampoco somos unos expertos! Simplemente queremos mostrar una comparativa de cual es la curva de aprendizaje o la facilidad con la que estos frameworks permiten empezar de 0.

## Información adicional

Necesitaríamos simplemente un proyector.

## Sobre mí

Este taller lo impartiría Afaya. Afaya somos Juan Manuel Rodríguez Pérez y Azahara Fernández Guizán, desarrolladores .Net MVC y conocidos de AsturiasHacking.

**Comment by sergioalvz** [comment]
Hola! Gracias por la propuesta 🎉 como veréis, tenemos el roadmap de eventos a _full_ hasta principios de junio. ¿Os caería bien esa fecha para realizar la actividad?

Un saludo!

**Comment by azaharafernandezguizan** [comment]
Hola,

Nosotros sin problemas, como si la necesitáis aplazar hasta después del
verano. Para cuando no tengáis ponencia 😀
