### ISSUE TITLE
Introducción a GraphQL

### ISSUE THREAD

**Issue by mcdave** [asturiashacking/activities#26]
# Propuesta de Actividad

## Título

Introducción a GraphQL

## Descripción

Introducción a GraphQL.
Comparación con APIs REST.
Beneficios para el front end.
Caso de uso en producción.
Q&A

## Nivel

Nivel introductorio.

## Sobre mí

Me llamo David, soy front end en spotahome y llevo ya varios años trabajando con React, GraphQL, BFFs y micro servicios.

**Comment by sergioalvz** [comment]
¡Muy buena pinta @mcdave! ¿Cómo estarías de disponibilidad para poder impartirla? Tenemos ocupados los dos huecos de Junio pero, a partir de ahí, por nosotros cuando quieras :)

Gracias!

**Comment by mcdave** [comment]
@sergioalvz yo creo que para Julio bien

**Comment by sergioalvz** [comment]
Hola @mcdave, ¿qué te parecería el jueves 12 de julio?

Un saludo!

**Comment by sergioalvz** [comment]
Finalmente, el evento ha sido publicado para el jueves 19 de julio: https://www.meetup.com/AsturiasHacking/events/251636743/ 👏
