### ISSUE TITLE
Discovering modern JavaScript, guided by tests

### ISSUE THREAD

**Issue by sergioalvz** [asturiashacking/activities#30]
# Propuesta de Actividad

## Título

Discovering modern JavaScript, guided by tests

## Descripción

_Workshop_ para descubrir las nuevas características del lenguaje. Utilizaremos una kata y un desarrollo dirigido por pruebas para ir descubriendo, a su paso, las nuevas adiciones a la especificación (operadores, sintaxis, mecanismos para gestionar código asíncrono, etc)

## Nivel

Creo que sería apto para cualquier persona que haya tenido ya cierto acercamiento al lenguaje (conozca su sintaxis y haya programado algo con él, principalmente).

## Información adicional

- Conexión a Internet
- Mesas y espacio de trabajo para los asistentes
- Proyector

## Sobre mí

Me llamo Sergio y organizo AsturiasHacking desde hace un par de años. Llevo trabajando con JavaScript desde hace más o menos 5 años, tanto en la parte de cliente como de servidor. [**`@codecoolture`**](https://twitter.com/codecoolture) en Twitter

**Comment by ulisesyo** [comment]
Cuando se va a hacer esta? ;)
Yo estaría más que interesado

**Comment by sergioalvz** [comment]
Buenas @ulisesyo ! Pues de momento fecha incierta, necesito sacar algo de tiempo para prepararlo bien... ¿quizás apuntando a febrero - marzo?

De todos modos, repasando la descripción, creo que voy a tener que actualizar la sección _Nivel_, es posible que cierto conocimiento (al menos superficial) de JavaScript sea necesario, porque no creo que me pueda detener a introducir el propio lenguaje, explicar sintaxis, etc.

Thanks por el apoyo, una inyección de motivación para prestarle atención! 😉

**Comment by ulisesyo** [comment]
@sergioalvz , como va este tema?? O se ha convertido en el curso de TDD?? ;)

**Comment by dcarral** [comment]
@sergioalvz Ahí va otra inyección (de motivación, lo del tiempo complicado :)), tiene pintaca máxima ;)

**Comment by sergioalvz** [comment]
Cierro el issue tras asumir que no voy a tener tiempo en el medio plazo para prepararlo bien. No quiero que esté aquí tomando espacio y generando ruido... 😞
