### ISSUE TITLE
Sesgos cognitivos en las pruebas. el lado más humano del testing

### ISSUE THREAD

**Issue by morvader** [asturiashacking/activities#34]
# Propuesta de Actividad

## Título
Sesgos cognitivos en las pruebas. el lado más humano del testing

## Descripción

Algo inherente a los seres humanos es que nuestras experiencias pasadas, educación, relaciones y otros muchos factores se acaban traduciendo en una serie de sesgos cognitivos que, casi de manera imperceptible, tienen gran peso en las decisiones que tomamos a diario. 

En esta charla veremos de qué manera afectan algunos de estos sesgos a nuestro trabajo a la hora de hacer pruebas y formas de mitigarlos.

## Nivel

No será una charla técnica. Es válida para cualquier perfil (no solo testers ) y nivel 

## Información adicional

Sala con proyector

## Sobre mí

Soy Francisco Moreno (Fran), PMP , Scrum Master y actualmente QA Lead en Sngular. 
Llevo los úlitmos 10 años dedicándome a temas relacionado con el testing y la calidad, tanto a nivel de definión de proceso, testing exploratorio como automatización de pruebas.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: TERMS.md

**Comment by sergioalvz** [comment]
¡Qué buena pinta @morvader! Gracias 👏

**Comment by azaharafernandezguizan** [comment]
Muy interesante!

**Comment by sergioalvz** [comment]
Hola @morvader! ¿Como ves Mayo como fecha para impartir esta ponencia? 

Un saludo!

**Comment by morvader** [comment]
Buenas @sergioalvz . Crees que habría interés en esta charla?. Al no ser algo puramente técnico me surge alguna duda. Podríamos sondear el interés de alguna manera?

Si no, podría transformase el ago tipo debate sobre los sesgos a la hora de producir software en general.

Ya me dices y gracias!

**Comment by sergioalvz** [comment]
La verdad, no veo porqué no podría haber interés. Hay un  buen número de reacciones y a mí (personalmente) me parece un tema interesante!

De todos modos, si prefieres un formato más distendido, podríamos también plantearlo como lean-coffee :)

**Comment by morvader** [comment]
@sergioalvz en cuanto a la fecha, por mi parte Mayo está bien.

Cuando se acerque la fecha si quieres valoramos el formato. Me vale cualquiera de los dos.

**Comment by sergioalvz** [comment]
@morvader vale Fran, como tu estés más cómodo / se te apetezca más :)

De momento, [pillado sitio en el calendario](https://www.meetup.com/AsturiasHacking/events/258122372/).

Gracias!
