### ISSUE TITLE
Formularios en React

### ISSUE THREAD

**Issue by mcdave** [asturiashacking/activities#35]
# Propuesta de Actividad

## Título

Formularios en React

## Descripción

introducción y experiencia usando formulario en una aplicación en producción.

Una parte básica de las aplicaciones es capturar información del usuario y para eso se usan formularios. 

En esta charla vamos a dar una vuelta a las opciones que tenemos en react y las experiencias que he tenido trabajando con diferentes enfoques. 

## Nivel

introducción

## Sobre mí

Me llamo David y trabajo como front end developer en spotahome 

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: TERMS.md

**Comment by m1guelpf** [comment]
Haría falta entender algo de React para asistir/enterarse?

**Comment by sergioalvz** [comment]
Hola @mcdave, ¿qué te parece enero de 2019?

**Comment by sergioalvz** [comment]
Ya en [el calendario de actividades](https://www.meetup.com/AsturiasHacking/events/257791771/) 🎉
