### ISSUE TITLE
Haciendo un "Dashboard" en tiempo real con Laravel, Vue, Pusher y Tailwind

### ISSUE THREAD

**Issue by m1guelpf** [asturiashacking/activities#39]
# Propuesta de Actividad

## Título

Haciendo un "Dashboard" en tiempo real con Laravel, Vue, Pusher y Tailwind

## Descripción
![Dashboard](https://user-images.githubusercontent.com/23558090/49346272-2ddd4700-f690-11e8-8d21-6090c8344236.png)
La charla consistirá en explicar como funciona cada componente de este dashboard ([basado en un proyecto de código abierto](https://github.com/spatie/dashboard.spatie.be)), incluyendo obtención de menciones en Twitter e interacción con varias APIs, actualización en real-time con websockets, y diseño con Tailwind (tratandolo todo un poco por encima). 

## Nivel

No voy a hablar de nada muy específico, la idea es explicar las tecnologías y como funciona todo un poco por encima.

## Información adicional

Haría falta un proyector y conexión a internet (y un adaptador si el proyector no tiene HDMI).

La charla esta inspirada en una [charla en LaraconEU por el autor del proyecto original](https://www.youtube.com/watch?v=jtB_rTh61Zo).

## Sobre mí

Me llamo Miguel y tengo 16 años. Dedicar mi tiempo libre a programar y a trabajar en demasiadas cosas a la vez. Llevo bastante tiempo queriendo dar una charla, y como últimamente he estado trabajando bastante en este proyecto me parecio que sería un buen tema para empezar :)

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by m1guelpf** [comment]
@anibalsanchez Perdona, ya está corregido

**Comment by anibalsanchez** [comment]
Ahora, Si ! Gracias

**Comment by sergioalvz** [comment]
Hola @m1guelpf, ¿qué tal ves el jueves 24 de enero?

Un saludo!

**Comment by azaharafernandezguizan** [comment]
Hola @m1guelpf ¿te apetecería impartir esta charla en Junio?

**Comment by azaharafernandezguizan** [comment]
Hola @m1guelpf ¿sigues interesado en impartir esta charla?

**Comment by m1guelpf** [comment]
Buenas @azaharafernandezguizan, perdona por el silencio pero estoy bastante liado con el cole ahora mismo

**Comment by azaharafernandezguizan** [comment]
No te preocupes @m1guelpf, cuando vuelvas a tener tiempo aquí nos tienes y mucho ánimo con los estudios!!

**Comment by azaharafernandezguizan** [comment]
Hola! Con la llegada de 2020, hemos pensando en mejorar nuestros eventos y creemos que podríamos ajustar la duración de las charlas para tener mas de una por sesión. También nos gustaría no acumular durante mucho tiempo las propuestas abiertas para que los ponentes que hacéis la labor de proponerla no tengáis que esperar mucho para impartirlas. Discúlpanos si en el caso de esta propuesta ha sido así... Si no tienes ahora disponibilidad para darla en el corto/medio plazo, ¿te parece si la cerramos moméntaneamente y cuando vuelvas a tener tiempo/ganas la volvemos a abrir? Nos encantaría seguir contando con tu colaboración!

**Comment by m1guelpf** [comment]
Si claro, sin problema!
