### ISSUE TITLE
(Charla/discusión) What is (not) Software Crafting?

### ISSUE THREAD

**Issue by dcarral** [asturiashacking/activities#4]
# Propuesta de Actividad

## Título

What is (not) Software Crafting?

## Descripción

Esta charla fue inicialmente preparada para el _Ruby User Group_ de Berlín, en Septiembre de 2017. Esta es la descripción original:

> What do we mean by Software ~~Craftsmanship~~ Crafting? What not? How and why was it born? Why does it matter?
> 
> After answering all these questions and introducing concepts like deliberate practice and Open Space Technology, we will explore the current status of Software Craftsmanship communities and events around Europe.

## Nivel

No es necesario ningún tipo de conocimiento previo. Debido al formato dinámico / interactivo de la charla, podemos profundizar en aquellos conceptos que resulten más desconocidos para la audiencia ;) 

## Sobre mí

Fascinado por la calidad del código y el aprendizaje continuo, convencido de las prácticas promulgadas por eXtreme Programming, amante de la filosofía detrás del software libre y participante habitual en la comunidad de artesanos de software y el grupo de usuarios de Ruby en Berlín.

Después de trabajar en Avilés para CSC Spain y en Gijón para Sweetspot, me mudé a Berlín fascinado por el constante intercambio de conocimiento por parte de las diferentes comunidades y grupos de usuarios allí existentes. Trabajé para Babbel durante un año y medio (primero como parte del equipo de Payments/Monetization y más tarde en un proyecto de R&D sobre adaptive learning aplicado a la enseñanza digital de lenguajes), para después embarcarme en lo que se conoce (en “términos artesanos”) como “journeyman tour”. 

En la actualidad mi mochila y yo nos dedicamos a recorrer mundo: compartiendo aventuras y buen rollo con diferentes comunidades locales de software, a través de charlas, talleres y, habitualmente, cerveza artesana :)

Muy feliz de ver _AsturiasHacking_ a pleno rendimiento, kudos Sergio / Manu! ;)

**Comment by sergioalvz** [comment]
¡Gracias por la propuesta, @dcarral! ¿Cuándo crees que podríamos buscar un hueco para llevarla a cabo?

Un saludo!

**Comment by dcarral** [comment]
¿Noviembre? Una o dos semanas antes del GDCR sería perfect ;)

**Comment by tasugo** [comment]
Muchas gracias por la propuesta, @dcarral!

Estaría guay la semana antes del code retreat, o incluso esa misma semana, a ver si conseguimos un efecto llamada de la charla para el eventillo :dancer:

**Comment by sergioalvz** [comment]
Parece que tenemos un ganador para el jueves 9 de noviembre :) Ahora sólo queda buscar un sitio adecuado para la ocasión 😉 Mis puntos irían para La Revoltosa o El Picalín.

**Comment by sergioalvz** [comment]
Fijado y -casi- publicado para el día 7 de noviembre! :)
