### ISSUE TITLE
Lean coffee para celebrar el el Día Internacional de la Mujer y la Niña en la Ciencia

### ISSUE THREAD

**Issue by azaharafernandezguizan** [asturiashacking/activities#40]
# Propuesta de Actividad

## Título

Lean coffee para celebrar el el Día Internacional de la Mujer y la Niña en la Ciencia

## Descripción

El 11 de Febrero se celebra el Día Internacional de la Mujer y la Niña en la Ciencia. Actualmente hay muchas iniciativas para promover una mayor representación femenina en el sector tecnológico. 
Propongo la realización de un lean coffee, para que entre todos generemos un debate en el cual desde el respeto y cumpliendo el código de conducta podamos hablar sobre el tema cómodamente. En el lean coffee cada cual propondrá algún aspecto a debatir sobre esta temática y podremos entre todos llegar a conclusiones o incluso propuestas para mejorar la situación. Creo que puede ser más participativo que una mesa redonda.

## Nivel

Apto para todos los niveles.

## Información adicional

No haría falta nada más que ganas de escuchar diferentes puntos de vista y de encontrar posibles soluciones o puntos a mejorar.

## Sobre mí

Soy Azahara Fernández Guizán, desarrolladora de software en Sngular y Asturhacker de corazón. 

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by sergioalvz** [comment]
Ya [está en el calendario](https://www.meetup.com/AsturiasHacking/events/257929981/).
