### ISSUE TITLE
Dos proyectos y un destino: JavaScript on Things

### ISSUE THREAD

**Issue by jmrp81** [asturiashacking/activities#41]
# Propuesta de Actividad

## Título

> Dos proyectos y un destino: JavaScript on Things

## Descripción

> En esta charla intentaremos describir el camino recorrido para comprobar la posibilidad de utilizar JavaScript en desarrollos de IoT. Los proyectos que hemos creado, o que estamos en proceso de creación (estarán listos para Junio) son: una mini-máquina retro del típico juego Snake y  un InmunoGame, juego tipo trivial donde la respuesta correcta te la proporciona una máquina diseñada por nosotros.

Los proyectos están construidos sobre Arduino y Rapsberry Pi y llevaremos los prototipos para mostrarlos en directo.

## Nivel

Explicaremos de forma muy sencilla los componentes que utilizamos, que pasos realizamos y mostraremos un poco de código pero sin llegar a abrumar. Se trata de una introducción al mundo IoT y como puede realizarse con Javascript.

## Información adicional

Necesitaremos un proyector para conectar el portátil y enseñar la presentación y nos gustaría que la charla fuese para mediados-finales de Junio o si no fuese posible para después del verano, para tener finalizados ambos proyectos y poder enseñarlos.

## Sobre mí

Esta charla la impartiremos Juan Manuel Rodríguez Pérez y Azahara Fernández Guizán (Afaya). Somos dos desarrolladores de software que en nuestros ratos libres frikeamos con varias tecnologías y participamos habitualmente en AsturiasHacking.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hemos pensado que como la han aceptado en tantos eventos y va a estar disponible online, quizás podamos darle una vuelta de tuerca tras el otoño y hacerla en formato taller, por si a alguien le apetece llevarse la Raspberry Pi y programar algo sencillo con Node o JavaScript, o vernos hacerlo allí mismo. Algo en formato distendido y ameno.

**Comment by azaharafernandezguizan** [comment]
Cerrado porque ya hemos impartido un kit y como la estamos dando en eventos y está siendo grabada va a ser muy repetitiva
