### ISSUE TITLE
Taller Introducción Kotlin 

### ISSUE THREAD

**Issue by tolbier** [asturiashacking/activities#42]
# Propuesta de Actividad

## Título

Taller Introducción  a Kotlin (no sólo para programadoras Java)

## Descripción

 Taller / Desayuno en el que se hará una introducción al lenguaje Kotlin (corriendo sobre JVM).
El formato se saldría un poco del habitual en Asturias Hacking, y necesitaría de 2-3 horas, preferentemente un sábado. El lugar, podría buscarse una cafetería o sitio similar donde poder desarrollar la actividad tras un desayuno común

En Programación por pares, empezar por los Kotlin Koans, dar un poco de teoría de los fundamentos de Kotlin, y acabar con  alguna kata de Codewars

(Wikipedia) : Kotlin es un lenguaje de programación de tipado estático con inferencia de tipos que corre sobre la máquina virtual de Java y que también puede ser compilado a código fuente de JavaScript. Está desarrollado principalmente por JetBrains
 
## Nivel

 Orientado a cualquier desarrolladora, aunque puede resultar especialmente interesante para programadoras Java, tanto BAK como Android. 
Se trabajaran conceptos básicos de programación funcional, pero no es necesario tener conocimientos previos de este paradigma.

## Información adicional

 Recomendable que cada asistente lleve su portatil con Intellij Community Edition (o Ultimate), Plugin EduTools instalado, y Kotlin Koans instalado
https://kotlinlang.org/docs/tutorials/koans.html

Asimisimo, también recomendable tener cuenta creada en codewars.com

Sería necesario un espacio con Wifi para todos los equipos, y mesas dispuestas para 2 personas cada una 

## Sobre mí
Lluis Toyos
  Senior Backend at ninetynine.com
 
 - https://www.linkedin.com/in/lluistoyos/
 - http://tolbier.com
 - [TEDX Gijon2014]( https://www.youtube.com/watch?v=7qqZGk5NzYU )

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by sergioalvz** [comment]
Suena interesante @tolbier ! Gracias por la propuesta, le buscaremos encaje.

**Comment by tolbier** [comment]
Os agradecería me dijerais "si sí o si no" cuando fuera posible..para poder hacerlo pronto, o sino buscaría alguna otra opción

Muchas gracias.

**Comment by sergioalvz** [comment]
Hola @tolbier, no podemos asegurarte hacerlo pronto. Por lo que puedes buscar otra opción sin problema. Avísanos por aquí de todos modos, para tenerlo cuenta :)

Gracias!

**Comment by azaharafernandezguizan** [comment]
Hola @tolbier me suena que finalmente este ya lo impartiste en otro meetup ¿no? ¿Sigues interesado en darlo de nuevo? Lo único que gestionar un sábado va a ser algo complejo por el tema espacios

**Comment by tolbier** [comment]
Vaya...encantao... Todavia tengo la presentacion por ahí. ..

La hice una vez ya con el GDG, pero no tuve mucho tiempo para hacerla
calmada. La presentacion es coger el código de la "intro to kotlin" de la
google io17 y hacerlo paso a paso...

 Da para 45minutos tranquilamente. Tambien se puede hacer un tallar
practico siguiendo las KotlinKoans.. y aprender el lenguaje solucionando
las Koans.

Un placer...total disponibilidad

**Comment by azaharafernandezguizan** [comment]
Realizado el martes 29 de Octubre. Gracias Lluis por enseñarnos como es Kotlin.
