### ISSUE TITLE
Edición colaborativa de textos con Swell

### ISSUE THREAD

**Issue by pablojan** [asturiashacking/activities#44]
# Propuesta de Actividad

## Título

Herramientas libres de colaboración con Swell

## Descripción

Las herramientas de colaboración son fundamentales, pero cada vez existen menos alternativas FLOSS (Free/Libre Open Source Software). 

Compartir y redactar textos entre varias personas en tiempo real es una forma básica de colaboración, que generalmente está disponible sólo en servicios cerrados y/o pesados como Google Docs, Office 365, Dropbox...

En esta charla presentaré el proyecto Swell (https://github.com/swellrt) un API para aplicaciones Web con edición de texto y colaboración en tiempo real. También me gustaría abrir un debate sobre  herramientas de colaboración y  Software Libre/Open Source.

Invito a todas y todos a hackear un rato y contribuir al proyecto.

Una aplicación de ejemplo realizada con Swell es el editor colaborativo [JetPad](https://jetpad.net/edit/asturiashackingjetpadissue)

## Nivel

Cualquier interesada en Software Libre, derechos digitales, programadores, etc. La intención inicial no es mostrar código o programar salvo que interese mucho a los asistentes.

## Información adicional

> ¿Es necesario tener en cuenta algún requisito para realizar la actividad? (mesas, conexión a Internet, un entorno preparado con antelación, etc.)

Mesas, conexión a Internet y proyector.

## Sobre mí

> ¡Ayúdanos a conocerte! Aprovecha esta sección para explicar quién eres, tu experiencia y cualquier otra información relevante para la comunidad

Soy programador, activista digital y surfista, y en mis ratos profesionales dirijo proyectos tecnológicos.  Me gusta estudiar e investigar sobre colaboración y participación en comunidades y organizaciones y sus herramientas. 

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by pablojan** [comment]
Hola! os conocí en el último meetup y me gustaría proponeros esta charla/debate ¿qué os parece? feedback welcome! gracias

**Comment by Jonatanmdez** [comment]
A mi me parece super interesante y fresco el tema :). Cuenta con mi presencia !

**Comment by sergioalvz** [comment]
Hola @pablojan, gracias por la propuesta :) 

¿Qué te parece mediados de mayo o finales de junio para realizar la actividad?

Un saludo!

**Comment by pablojan** [comment]
Hola @sergioalvz, gracias a vosotras por dar un espacio para tratar estos temas.

Me viene mejor a finales de junio. Mayo será un mes complicado para mi. Entiendo que iremos cerrando la fecha más adelante y seguro que nos veremos antes.

Gracias @Jonatanmdez por tu respuesta!

**Comment by azaharafernandezguizan** [comment]
Hola @pablojan ¿que te parecería a mediados de Junio? ¿Te vendría bien?

**Comment by pablojan** [comment]
En junio perfecto!

**Comment by azaharafernandezguizan** [comment]
Meetup realizado y con un networking muy ameno
