### ISSUE TITLE
GitKraken Git GUI vs CLI

### ISSUE THREAD

**Issue by sergupe** [asturiashacking/activities#45]
# Propuesta de Actividad

## Título

> GitKraken Git GUI vs CLI

## Descripción

> Si eres desarrollador de software, seguro que utilizas/has utilizado la consola de comandos para gestionar tus repositorios. Y es que la mayoría de los desarrolladores consideran que manejar la consola de comandos prueba que tienes muchos conocimientos y habilidades, mientras que otros simplemente piensan que utilizar la consola te hace mejor desarrollador.
Pero, en un mundo de constante cambio, donde todo avanza y se actualiza a velocidades increíbles... ¿Por qué no probar una GUI? ¡Acompáñame en esta pequeña charla y te demostraré todo el potencial de GitKraken y la comodidad y facilidad de su uso!
Sería una pequeña charla de en torno a 30-40 minutos de duración.

## Nivel

> Apta para todo aquel que pertenezca al mundillo de la programación y trabaje con sistemas de control de versiones.

## Información adicional

> De momento no es necesario material extra, más adelante lo confirmaré.

## Sobre mí

> Mi nombre es Sergio Gutiérrez y soy desarrollador de I+D en Mecalux Software Solutions y embajador de marca para GitKraken. Llevo trabajando con control de versiones desde hace unos 4 años y me gusta divulgar y comentar sobre todo aquello que me parece beneficioso para todos en nuestro ámbito del desarrollo de software.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by sergioalvz** [comment]
Hola @sergupe ! Gracias por la propuesta 👏 👏

**Comment by sergupe** [comment]
Gracias a vosotros por los meetups!!

**Comment by azaharafernandezguizan** [comment]
Hola @sergupe , ¿esta propuesta ahora te quedamos un poco lejos físicamente no?

**Comment by azaharafernandezguizan** [comment]
Hola! Con la llegada de 2020, hemos pensando en mejorar nuestros eventos y creemos que podríamos ajustar la duración de las charlas para tener mas de una por sesión. También nos gustaría no acumular durante mucho tiempo las propuestas abiertas para que los ponentes que hacéis la labor de proponerla no tengáis que esperar mucho para impartirlas. Discúlpanos si en el caso de esta propuesta ha sido así... Si no tienes ahora disponibilidad para darla en el corto/medio plazo, ¿te parece si la cerramos moméntaneamente y cuando vuelvas a tener tiempo/ganas la volvemos a abrir? Nos encantaría seguir contando con tu colaboración!

**Comment by sergupe** [comment]
Sin problema Azahara!! Ahora mismo ando liadillo en el trabajo, así que
mejor cerrarla de momento y la preparo en cuanto disponga de más tiempo.

**Comment by azaharafernandezguizan** [comment]
Cerrada por el momento!
