### ISSUE TITLE
Como hacer videojuegos "like a pro"

### ISSUE THREAD

**Issue by ulisesyo** [asturiashacking/activities#46]
# Propuesta de Actividad

## Título

> Cómo hacer videojuegos "like a pro"

## Descripción

> Charla de introducción a Unity, uno de los motores de videojuegos más usados actualmente.. Veremos un poco "de qué va esto" de hacer videojuegos, diferencias respecto a otro tipo de aplicaciones, setup estandar para poder empezar a desarrollar y alguna que otra anécdota. También veremos la API de Unity muy por encima, y ejecutaré algo de código para ver como funciona en tiempo real.

## Nivel

> Va a ser una charla muy coloquial y muy introductoria. Lo importante será tener ganas de aprender y de intercambiar ideas. Todo el mundo está invitado a venir, pero si sabes un poco de programación, mejor que mejor...

## Información adicional

> ...
## Sobre mí

> Ulises Martínez, desarrollador desde 2007, año en el que termine la carrera. Me fui a Madrid, volví a Asturias, monté 2 empresas y ahora soy freelance.. He trabajado en videojuegos, tecnologías 3D toda mi vida, ahora también trabajo en apps móviles :)

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola! Con la llegada de 2020, hemos pensando en mejorar nuestros eventos y creemos que podríamos ajustar la duración de las charlas para tener mas de una por sesión. También nos gustaría no acumular durante mucho tiempo las propuestas abiertas para que los ponentes que hacéis la labor de proponerla no tengáis que esperar mucho para impartirlas. Discúlpanos si en el caso de esta propuesta ha sido así... Si no tienes ahora disponibilidad para darla en el corto/medio plazo, ¿te parece si la cerramos moméntaneamente y cuando vuelvas a tener tiempo/ganas la volvemos a abrir? Nos encantaría seguir contando con tu colaboración!
