### ISSUE TITLE
Cabeceras HTTP para mejorar la seguridad de cualquier aplicación web

### ISSUE THREAD

**Issue by jose-r-lopez** [asturiashacking/activities#47]
# Propuesta de Actividad

## Título

> Cabeceras HTTP para mejorar la seguridad de cualquier aplicación web

## Descripción

> Quisiera hacer una charla acerca de las cabeceras HTTP que implementa este protocolo relativas a seguridad, y como se pueden usar para mejorar ciertos aspectos de seguridad de cualquier aplicación servida, independientemente de la tecnología usada para el desarrollo (ya que estas cabeceras actuan a nivel de protocolo).

## Nivel

> Creo que cualquier persona que haya implementado una aplicación web se podrá beneficiar de su contenido. Solo es necesario unos rudimentos de como funciona el protocolo HTTP que incluso se podrían explicar en muy poco tiempo.

## Información adicional

> No, solamente un visor de PDF. Se podría ver algo en vivo si fuera necesario, para ello se necesitaría una conexión a Internet y un navegador estandar, ya que se pueden observar las cabeceras en uso en cualquier web a la que se acceda.

## Sobre mí

> Soy Doctor en Informática y profesor del Máster en Ingeniería Web de la Universidad de Oviedo, especializado en temas de administración y seguridad. Llevo impartiendo esta asignatura unos 13 años, y trato de mantenerla todo lo actualizada que me es posible. Una de las incorporaciones que hice hace 3 años fue este tema, que ha sido bien recibido por el alumnado debido a que se aplica a cualquier tecnología. Me gusta mucho dar clases y charlas, y quisiera "probar suerte" en otros entornos más "públicos".

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Impartido el jueves 12 de diciembre de 2019
