### ISSUE TITLE
De la orientación a objetos a la programación funcional: un viaje alucinante

### ISSUE THREAD

**Issue by iquesada** [asturiashacking/activities#48]
# Propuesta de Actividad

## Título

De la orientación a objetos a la programación funcional: un viaje alucinante

## Descripción

Charla sobre cómo adentrarse en la programación funcional viniendo de la orientación a objetos. Está basada en mi experiencia personal, y trata de describir las características fundamentales de la programación funcional, y por qué debería ser tenida en cuenta como una opción más.
La charla es totalmente agnóstica de lenguajes, centrándose exclusivamente en los paradigmas. No obstante, no se descarta alguna pincelada de Elixir.

## Nivel

Unos conocimientos básicos de programación son suficientes para disfrutar de la charla. Se abordará la programación funcional desde cero.

## Información adicional

Necesitaría un proyector para las slides.

## Sobre mí

Me llamo Iñaki y llevo trabajando como desarrollador de backend unos cuantos años, sobre todo en Ruby on Rails. Actualmente trabajo en Elixir. Puedes encontrarme en Twitter como @piedresybarro

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Cierro esta actividad que por cierto tuvo mucho éxito, que suerte contar con Iñaki!
