### ISSUE TITLE
Nuestras referentes femeninas en STEM

### ISSUE THREAD

**Issue by azaharafernandezguizan** [asturiashacking/activities#49]
# Propuesta de Actividad

## Título

Nuestras referentes femeninas en STEM

## Descripción

Propongo una actividad para la semana del 11 de Febrero, día internacional de la mujer y la niña en STEM, en el que nos reunamos para recopilar todas aquellas referentes en STEM que tenemos en nuestro día a día. Mi propuesta es que cada participante que le apetezca lleve pensada una mujer que trabaje en STEM que le resulte inspiradora y rellene una plantilla muy sencilla con la información de la misma. Estas plantillas las recopilaremos y se proyectarán el día del meetup, siendo cada participante quien nos cuente un poco más de cada mujer. Serán participaciones cortas (3-5 minutos) y la plantilla será muy sencilla. Luego podemos recopilarlas todas y publilcarlas.

## Nivel

No hace falta nivel, sólo ganas de compartir referentes y descubrir nuevos. Estaría genial si además cada participante trajese a algún invitado o invitada aunque no fuese del sector tecnológico.

## Información adicional
Necesitamos un proyector y una sala con sillas para crear un ambiente distendido

## Sobre mí

Soy Azahara Fernández, desarrolladora de software y doctora en Inmunología. Formo parte de AsturiasHacking, de Afaya y siempre trato de ayudar donde se me necesite.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by dcarral** [comment]
@rachelcarmena Muuuuuuuuuuu :)

**Comment by dcarral** [comment]
A pesar de que el ˝Muuuuuuuuuuu˝ a @rachelcarmena no fue motivo suficiente para que nos visitase, o al menos saludase vía GitHub… el evento fue completamente TOP y, personalmente, creo que de los más importantes a los que he asistido últimamente.

Enhorabuena @azaharafernandezguizan & @sergioalvz, #respect + ¿slides disponibles somewhere?

**Comment by azaharafernandezguizan** [comment]
Hola @dcarral vamos a tratar de subirlas a la web y hacer el formulario vivo, tal como se propuso, pero necesitamos algo de tiempo para que quede chulo. Prometemos tenerlo disponible.

**Comment by dcarral** [comment]
Entiendo que eso es un no :P Quedo a la espera para compartir la página web (ideaca btw ;)) pues. Gracias por la respuesta Azahara, un saludín.
