### ISSUE TITLE
(Workshop/sesión práctica) What is “good code”? Evaluating code quality

### ISSUE THREAD

**Issue by dcarral** [asturiashacking/activities#5]
# Propuesta de Actividad

## Título

_What is “good code”? Evaluating code quality_

## Descripción

Esta sesión fue inicialmente facilitada durante el _SoCraTes Day Berlin_, en Octubre de 2017. Esta es la agenda / tabla de contenidos:

> 1. (Intro) Introduction to the problem: what is “good code”?
> 2. (Craft) Solve a simple algorithmic problem.
> 3. (Show) Discuss the (probably) different approaches we came up with. 
> 4. (Discuss) 
>     - Evaluation based on opinion vs facts: introduction to static code analysis / software metrics.
>     - Take a look at more potential solutions, what do the numbers say?
>     - Final remarks / discussion.

## Nivel

Dirigido a programadores, no obstante no se requiere ningún tipo de conocimiento / experiencia previa.

### Duración 

1 hora y media sería ideal, pero lo podemos adaptar al tiempo del que dispongamos.

### Espacio

Con:

  - Conexión a Internet
  - Proyector (opcional, nos apañamos sin él)
  -  _Flipchart_ (opcional, nos apañamos sin él)

### Participantes:

Con:

  - Portátil con **entorno de desarrollo preparado** (suficiente uno por cada dos asistentes)
  - Ganas de pasarlo bien (opcional, nos apañamos sin ellas ;))

Nota: La test suite está disponible en, al menos: _C, Clojure, Coffeescript, Lisp, C++, C#, JavaScript, Elixir, Erlang, F#, Go, Haskell, Java, Kotlin, Lua, Objetive-C, PHP, Python, Ruby, Rust, Scala, Swift, Typescript_.

## Sobre mí

Igual os sueno de https://github.com/asturiashacking/activities/issues/4 ([dcarral.org](https://dcarral.org)).

**Comment by sergioalvz** [comment]
Fijado y -casi- publicado para el día 7 de noviembre! :)

**Comment by sergioalvz** [comment]
Gracias de nuevo, @dcarral ! 😉
