### ISSUE TITLE
PowerPoint Karaoke

### ISSUE THREAD

**Issue by Jonatanmdez** [asturiashacking/activities#50]
# Propuesta de Actividad

## Título

PowerPoint Karaoke

## Descripción

PowerPoint Karaoke es una herramienta para mejorar nuestras habilidades dando charlas o hablando en público en general. Se basa en dar una charla utilizando unas presentaciones desconocidas para el ponente y tratando de que tenga sentido (por eso el karaoke).

La actividad sería por tanto que por turnos voluntarios (meter el nombre en una cajita de cartón) hubiese diferentes ponentes que dieran la charla sin conocer el contenido de la presentación. Serian unos 5 o 6 diapositivas por persona y por tanto unos 5-10 minutos por persona.

Es una actividad informal para romper el hierro y animarnos a hablar en público, aquí os paso un link de un ejemplo de un PowerPoint Karaoke : https://www.youtube.com/watch?v=znHXwrV6YQI ( no he podido encontrar nada en Español)

## Nivel

Conocimientos básicos del mundo software.

## Información adicional

Seria necesario un proyector e idealmente un aula pequeña para que todo sea más cercano, el objetivo es que la fricción sea mínima.

## Sobre mí

Me llamo Jonatan Menendez y trabajo en remoto como desarrollador Backend PHP. Me gustan los gatos y aportar a la comunidad.

**Comment by azaharafernandezguizan** [comment]
Cierro la issue, muchas gracias de nuevo @Jonatanmdez por la actividad!
