### ISSUE TITLE
Xtrem Reading: ¿leemos?

### ISSUE THREAD

**Issue by dcarral** [asturiashacking/activities#51]
# Propuesta de Actividad

## Título

_Xtrem Reading_: ¿leemos?

## Descripción

[_Xtrem Reading_](https://www.xtrem-reading.com/), actividad para leer varios libros en una hora de forma colaborativa.

¿Te resulta extraño? A nosotras también… ¿experimentamos? :)

## Duración

90 minutos

## Nivel

No relevante. Todas las personas interesadas en el desarrollo de software (aún desconociéndolo) son bienvenidas :)

## Información adicional

- Edificio y sala accesibles.
- Más allá de conocer el [código de conducta][code of conduct], sería conveniente acudir con un libro.
- Será divertido y aprenderemos una cosa o dos (o al menos lo intentaremos).
- Lo mencionado en https://github.com/asturiashacking/activities/issues/57 sobre seguridad psicológica, inclusión y diversidad también aplica aquí.

## Sobre mí

(esa cosa llamada bio…)
https://twitter.com/dcarral
(#4, #5, [Coderetreat](https://www.meetup.com/AsturiasHacking/events/244978487/) & [Open Space](https://www.meetup.com/AsturiasHacking/events/263548880/)). 

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by dcarral** [comment]
Fwiw hay gente en Asturias usando esto ya… quizás, si les engañamos, puedan facilitar elles y así seguimos añadiendo gente a la facilitators list? :-)

**Comment by azaharafernandezguizan** [comment]
Hola Dani, si no te importa vamos a postponer un poco esta actividad para ponerla quizás en Mayo-Junio? Me parece de hecho una actividad interesante para cerrar pre-verano ¿que opinas?

**Comment by dcarral** [comment]
Cuando queráis, aquí estamos para lo que sea, como siempre :)

Dicho esto, cierro la issue ya que, tras unas muy valiosas recientes conversaciones con @eferro, he decidido dar un paso atrás para ayudar a otras personas a dar varios hacia delante ;)

Fwiw en el book club organizado por PrivacyCloud llevamos varias semanas usando ˝Xtrem Reading˝ (os lo recomiendo), por lo que hay bastante/mucha gente en Asturias que ya está familiarizada con el formato y podría facilitar perfectamente esta sesión.
