### ISSUE TITLE
Taller Jetpack Compose

### ISSUE THREAD

**Issue by fercarcedo** [asturiashacking/activities#52]
# Propuesta de Actividad

## Título

Jetpack Compose: futuro de UI en Android

## Descripción

Este año 2019 hemos visto que Android y iOS están evolucionando hacia el desarrollo de interfaces de manera reactiva, de forma similar a frameworks web como React y basadas en código en lugar de los clásicos XML. En iOS tenemos SwiftUI y en Android Jetpack Compose.

En este taller se haría una introducción a Jetpack Compose en Android, presentando sus diferencias y conceptos fundamentales, y se haría una aplicación sencilla guiada a modo de ejemplo para verlo en acción.

## Nivel

El público ideal sería el que tenga conocimientos mínimos de Kotlin y Android, pero realmente no se necesitaría ningún conocimiento previo, se irían introduciendo los conceptos necesarios según vayan apareciendo.

## Información adicional

Recomendable que se lleven ordenadores con Android Studio 4.0 instalado y disponer de conexión a Internet.

## Sobre mí

Mi nombre es Fernando García Álvarez y actualmente estoy simultaneando estudios del segundo curso del Máster en Ingeniería Web de la Universidad de Oviedo y trabajo en un grupo de investigación de la Universidad. 

En cuanto a Android, tengo varias aplicaciones publicadas en Play Store ([https://play.google.com/store/apps/developer?id=Fernando+Garc%C3%ADa+%C3%81lvarez](https://play.google.com/store/apps/developer?id=Fernando+Garc%C3%ADa+%C3%81lvarez)), [https://play.google.com/store/apps/developer?id=FerJoGames](https://play.google.com/store/apps/developer?id=FerJoGames). Además, participé en el programa Google Summer of Code desarrollando Fretboard, un framework de testing A/B para Android escrito en Kotlin para Mozilla, en Firefox para Android. También, antes de incorporarme al grupo de investigación, estuve trabajando unos meses en la empresa Beleriand, y entre otras actividades hice desarrollo Android en Kotlin.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola, @fercarcedo. Como habrás visto vamos a empezar a unir varias charlas (acortando tiempos) en una sola actividad. Entendemos que tu propuesta está pensada para un taller y que llevará más tiempo, ¿nos puedes pensar en cuanto tiempo estabas pensando de duración el taller?

**Comment by fercarcedo** [comment]
Hola. Aunque lo ideal probablemente sería disponer de hacia 1h30, lo puedo acortar sin problema a 1h :)

**Comment by fercarcedo** [comment]
Y si os viene mejor por cuestiones de tiempo que sea en formato charla, por mi parte tampoco habría ningún problema

**Comment by azaharafernandezguizan** [comment]
Genial @fercarcedo y que mes te vendría mejor para impartirlo ¿Abril o Mayo?

**Comment by fercarcedo** [comment]
En abril tendría que ser después de Semana Santa, que estaré fuera. Aunque de poder elegir una fecha lo ideal sería hacerlo después del 15 de mayo, que así es después del Google I/O y podría actualizarlo con las novedades que presenten

**Comment by azaharafernandezguizan** [comment]
Vale pues si acaso lo dejamos para finales de Mayo, ¿te parece bien?

**Comment by fercarcedo** [comment]
Perfecto

**Comment by azaharafernandezguizan** [comment]
Hola @fercarcedo, el tema del coronavirus hizo que estos últimos meses no hayamos podido realizar meetups presenciales. El mes que viene es el último antes del parón veraniego, y vamos a aprovechar el verano para organizar el próximo trimestre.

Como ya hace mucho tiempo que se propusiste esta actividad, nos gustaría saber si sigues interesado en impartirla en otoño, si no es así puedes cerrarla o por ausencia de respuesta la cerraré yo en unos días. 

Gracias por todo!

**Comment by fercarcedo** [comment]
Hola. La verdad que ahora mismo no os puedo garantizar que pueda hacerla presencialmente en otoño, por lo que creo que en este caso lo mejor será cerrarla por ahora.

Muchas gracias por todo :)
