### ISSUE TITLE
Bilbostack 2020

### ISSUE THREAD

**Issue by Jonatanmdez** [asturiashacking/activities#54]
# Propuesta de Actividad

## Bilbostack

 El sábado 25 de Enero se realiza en Bilbao el [`BilboStack 2020`](https://bilbostack.com/).

## Descripción
 El objetivo de la actividad es animar a todo el mundo que quiera ir, pero no se atreva porque piense que va a estar solo, o por que no tenga medios para ir (el transporte en autobús creo que es bastante malo).

La idea es hacer una lista con las personas que van a ir (creo que va a ser una buena invasión asturiana) y ya organizarnos por privado el tema de compartir coche etc :) .

Es sobre todo animar a alguien que tenga dudas y nunca haya ido a un evento nacional a venir :) 

## Personas confirmadas para BilboStack 2020

1. @dcarral 
2. @azaharafernandezguizan 
3. @sergioalvz 
4. @jmrp81
5. @jonatanmdez
6. @fontecha
7. @SantiMA10

## Nivel

No hay nivel mínimo. Cualquier persona interesada en la tecnología puede acudir.

## Información adicional
Después del evento se va a comer pintxos y tomar algo todo juntos, no te lo puedes perder.

## Sobre mí

Me llamo Jonatan Menendez y trabajo en remoto como desarrollador Backend PHP. Me gustan los gatos y aportar a la comunidad.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by dcarral** [comment]
A mi también me gustan los gatos y aportar a la comunidad… 😂  … e iré al Bilbostack.

**Comment by sergioalvz** [comment]
Yo también he conseguido entrada 🎉  Todavía no me he decidido sobre cómo llegar a Bilbao ni cuánto tiempo estar...

**Comment by Jonatanmdez** [comment]
Yo en mi caso mi idea es ir y volver en el dia. A priori no llevo a nadie, así que por ahora tengo 4 huecos en el coche :)

**Comment by SantiMA10** [comment]
Yo aún estoy en lista de espera 🤞

**Comment by dcarral** [comment]
Fingers crossed x 100000 @SantiMA10.

_Fwiw_, después de recibir consejos de algunas personitas que han estado otros años en el _Bilbostack_, y con el objetivo de aprovechar el ambiente dinámico (aka flow) que se suele generar tomando _pintxos_ por Bilbo de tarde/noche, seguramente tire para allá el viernes y vuelva a la tierrina el Domingo por la tarde.

Si hay más gente interesada en pasar la noche del sábado por allí, se podría plantear compartir un piso, reservar habitas en el mismo sitio… ideas / food for thought.

¡Muchas ganas! :)

P.S.: ¿Será Bilbostack un buen momento para arrancar un club de fans astures de @eferro? 😆 😆

**Comment by dcarral** [comment]
FYI @Jonatanmdez #SantiSeViene  https://twitter.com/dcarral/status/1217023447097925632

**Comment by Jonatanmdez** [comment]
> FYI @Jonatanmdez #SantiSeViene https://twitter.com/dcarral/status/1217023447097925632

Actualizado :)

**Comment by dcarral** [comment]
Fwiw, visto vía https://twitter.com/bilbaoswcraft/status/1219195937635082241:

<img width="594" alt="Screenshot 2020-01-20 at 16 15 08" src="https://user-images.githubusercontent.com/1498567/72737570-1ddc3b80-3ba0-11ea-958f-aba68b1db99b.png">

**Comment by sergioalvz** [comment]
@todos: fue un placer coincidir con ustedes por allí :-)
