### ISSUE TITLE
Hacking tecnologías NFC

### ISSUE THREAD

**Issue by jonyluke** [asturiashacking/activities#55]
# Propuesta de Actividad

## Título

> Hacking tecnologías NFC

## Descripción

> Quisiera hacer una charla en la que explicaría que es el nfc, y en que partes de nuestra sociedad está presente, me centraré en la tecnología que más se suele usar de tarjetas inteligentes sin contacto, las mifare classic, desde explicar su historia (cifrado roto desde 2007 y aún 200 millones de tarjetas en uso) y como se almacenan los datos, hasta explicar los distintos ataques que este sufre (ej: descifrar las claves, clonado y emulación de tarjetas), que no solo puede afectar negativamente a las empresas si no a nosotros mismos, además de mostrar casos reales en los que se han producido ataques.

## Nivel

> No se necesita ningún conocimiento en especial.

## Información adicional

> Lo único necesario es proyectar un powerpoint.

## Sobre mí

> Soy Jonathan, estudiante de ingeniería informática y autodidacta de la ciberseguridad.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola Jonathan,
Muy buena propuesta. Estamos agendando las propuestas que teníamos ya en el repo para el primer trimestre. Nos gusta tu propuesta, así que te contactaremos para el siguiente trimestre y veremos que fecha te viene bien😁

**Comment by dcarral** [comment]
Qué guay Jonathan, suena súper interesante.

Cuenta con mi ayuda para preparar la charla, de NFC tengo poquita idea pero quizá pueda darte tips útiles a la hora de hablar en público o diseñar slides (spoiler: speaking.io 😄 ).

Looking forward!

**Comment by azaharafernandezguizan** [comment]
Hola @jonyluke estamos empezando a planificar las charlas de Marzo y Abril. Tal como anunciamos por Github, hemos pensado en cambiar la dinámica y unir dos charlas en un solo meetup. La idea sería que la charla durase 30 minutos, ¿tendrías disponibilidad en Marzo para impartirla en estas condiciones?

**Comment by jonyluke** [comment]
> Hola @jonyluke estamos empezando a planificar las charlas de Marzo y Abril. Tal como anunciamos por Github, hemos pensado en cambiar la dinámica y unir dos charlas en un solo meetup. La idea sería que la charla durase 30 minutos, ¿tendrías disponibilidad en Marzo para impartirla en estas condiciones?

Si puedo escoger prefiero hacerla en semana santa.

**Comment by azaharafernandezguizan** [comment]
Hola @jonyluke lo que vamos a hacer es según las preferencias que tengáis ir agrupando las charlas de dos en dos. Normalmente en AsturiasHacking usamos los jueves, pero se varía de día según las necesidades de los y las ponentes. Sobre Semana Santa, entiendo que estamos hablando de lunes a miércoles (los días festivos no es fácil encontrar espacios y además mucha gente está fuera con lo cual disminuye la afluencia).
¿Habría alguna otra fecha que te viniese bien, aunque hablásemos de Abril o Mayo? Es para tenerlo en cuenta.

**Comment by jonyluke** [comment]
> Hola @jonyluke lo que vamos a hacer es según las preferencias que tengáis ir agrupando las charlas de dos en dos. Normalmente en AsturiasHacking usamos los jueves, pero se varía de día según las necesidades de los y las ponentes. Sobre Semana Santa, entiendo que estamos hablando de lunes a miércoles (los días festivos no es fácil encontrar espacios y además mucha gente está fuera con lo cual disminuye la afluencia).
> ¿Habría alguna otra fecha que te viniese bien, aunque hablásemos de Abril o Mayo? Es para tenerlo en cuenta.
Entiendo, pues me viene bien cualquier miércoles de Marzo o Abril, y en Mayo cualquier día.

**Comment by azaharafernandezguizan** [comment]
Vale pues te voy apuntando para Marzo y te busco un compañero de charla, ¿entre miércoles 19 y miercoles 26 cual prefieres?

**Comment by jonyluke** [comment]
> Vale pues te voy apuntando para Marzo y te busco un compañero de charla, ¿entre miércoles 19 y miercoles 26 cual prefieres?

Prefiero el miércoles 25.

**Comment by azaharafernandezguizan** [comment]
Hola @jonyluke voy a reservar sitio y en cuanto lo tenga creo el meetup y te incluyo ¿me puedes pasar tu usuario de meetup por aquí o si quieres buscarme y enviarmelo por meetup para que sea mas privado?
Saludos

**Comment by azaharafernandezguizan** [comment]
Hola @jonyluke estamos empezando a planear con tiempo las charlas de los próximos meses, ¿podríamos enviarnos un mail a asturiashacking@gmail.com para seguir con el proceso de buscarle fecha? 
Gracias!

**Comment by azaharafernandezguizan** [comment]
Gracias por la charla!
