### ISSUE TITLE
5G "in a nutshell" y otros datos curiosos de las telecomunicaciones.

### ISSUE THREAD

**Issue by byDavid360** [asturiashacking/activities#56]
# Propuesta de Actividad

## Título

5G "in a nutshell" y otros datos curiosos de las telecomunicaciones.

## Descripción

Las llevamos usando cientos de años (de una forma u otra y con unos fines u otros) pero pocas veces no nos paramos a pensar cómo funcionan o qué son realmente las telecomunicaciones. Las malas lenguas dicen que es un tema muy dificil de estudiar (a veces no se equivocan) pero el concepto, bien explicado, no lo es tanto. Con esta actividad me gustaría compartir ciertos datos y curiosidades que aprendí en los 3 años que llevo estudiando Ingeniería de Telecomunicaciones y otros tantos más en los que me dediqué a leer, escuchar y preguntar al respecto.

## Nivel
No hacen falta conocimientos previos, ya que procuraré no entrar en tecnicismos. Solo muchas ganas de aprender y debatir.

## Información adicional
Se agradecería la disponibilidad de una pizarra y un proyector.

## Sobre mí

Me llamo David  y estoy cursando el tercer año de estudios de Ingeniería de Telecomunicaciones. A pesar de que me estoy especializando en Teoría de la Señal , estudio informática de forma autodidacta por internet.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Gracias David por la propuesta! Nos gusta mucho. Estamos agendando las propuestas anteriores para los primeros meses del año pero, sin duda, nos pondremos en contacto contigo mas adelante para previsiblemente el segundo trimestre.

**Comment by dcarral** [comment]
¡Suena fenomenal David! Cuenta conmigo para darte feedback sobre la sesión, ayudarte a prepararla, usarme de rubber duck, o cualquier otra cosa en la que te pueda echar una mano.

Por cierto, ¿te has planteado hacer algo similar en la uni, a través de delegaciones de alumnos o similar?

Looking forward! :-)

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360,  estamos empezando a planificar las charlas de Marzo y Abril. Tal como anunciamos por Github, hemos pensado en cambiar la dinámica y unir dos charlas en un solo meetup. La idea sería que la charla durase 30 minutos, ¿tendrías disponibilidad en Marzo para impartirla en estas condiciones?

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360  estamos planeando las actividades de los próximos meses, ¿tienes disponibilidad a partir de Abril?

**Comment by byDavid360** [comment]
> 
> 
> Hola @byDavid360 estamos planeando las actividades de los próximos meses, ¿tienes disponibilidad a partir de Abril?

**Comment by byDavid360** [comment]
Hola @azaharafernandezguizan A partir de Abril podría desarrollar mi actividad. Muchas gracias y lamento la tardanza en responder. Un saludo

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360 he visto que has cerrado la issue, ya no estas interesado en impartirla?
Normalmente las issues se cierran cuando el ponente no quiere darla o una vez se haya impartido.
Si deseas seguir con ella, reabrela o dimelo y la reabro yo.

**Comment by byDavid360** [comment]
@azaharafernandezguizan Perdona pero no sé qué toqué... Sí! Estoy interesado pero a la hora de responderte creo que cliqué donde no debía. Creo que la he vuelto a reabrir. Muchas gracias y disculpa las molestias...

**Comment by azaharafernandezguizan** [comment]
No te preocupes @byDavid360 , el mes que viene te contactaré de nuevo para ver si podemos juntar tu charla con la de otra ponente y hacer un meetup en Abril conjunto! :-)

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360 nos ha quedado un hueco libre para el meetup del 25 de Marzo, ¿esa fecha te vendría bien o lo dejamos para mas adelante como habíamos hablado? Un saludo

**Comment by byDavid360** [comment]
@azaharafernandezguizan  Hola Azahara! La verdad que me viene mejor un poco más adelante (tipo abril como habíamos hablado). De todas maneras muchas gracias por tenerme en cuenta. Un saludo!

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360 ,

¿Qué tal todo? Espero que dentro de la situación actual te encuentres bien y que tanto tú como tu familia tengáis buena salud.

Te escribo porque estamos pensando en retomar las sesiones de AsturiasHacking online pero de una forma diferente. Hemos pensado en mantener nuestra esencia y por ello, las sesiones serán online pero no se grabarán, tendrán un número limitado de participantes y además buscamos charlas cortas de 20-30 minutos para después tener un tiempo de networking. 

Nos preguntábamos si tu propuesta sigue en pie y si con estas condiciones te interesaría que la programásemos en los próximos meses.

Un saludo,
Azahara

**Comment by byDavid360** [comment]
Hola @azaharafernandezguizan estoy perfectamente! Espero que tú también. Agradezco mucho que hayáis invertido este esfuerzo extra en el programa y hayáis planteado una solución telemática (aunque a todos nos hubiese encantado vernos en persona ;-) ). Sin considerarme una excepción al resto, quiero aclararte que esta situación extraordinaria junto con una muy mala gestión por parte de la universidad en la que estudio ha hecho que me sea muy difícil dedicar todo el tiempo que me hubiese gustado a preparar mi intervención en este proyecto. Aún así, me encantaría que me tuvieses en cuenta para una próxima edición (ya sea virtual o física) que no se encuentre en este "periodo de exámenes" . Muchísimas gracias por tu tiempo y por tu atención Azahara. Un saludo!

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360 , no te preocupes. Como todos los años descansaremos en Julio y Agosto y volveremos tras el verano.
Vuelvo a contactarte entonces por si sigues interesado.

Y ¡mucho ánimo con los exámenes!

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360 estamos empezando a planear con tiempo las charlas de los próximos meses, ¿podríamos enviarnos un mail a asturiashacking@gmail.com para seguir con el proceso de buscarle fecha? 
Gracias!

**Comment by azaharafernandezguizan** [comment]
Hola @byDavid360, si sigues interesado en impartir esta propuesta escríbenos un correo a asturiashacking@gmail.com, sino en unos días cerraremos la propuesta :-)
