### ISSUE TITLE
Coding dojo: approval testing, refactoring, legacy code & friends

### ISSUE THREAD

**Issue by dcarral** [asturiashacking/activities#57]
# Propuesta de Actividad

## Título

Coding dojo: approval testing, refactoring, legacy code & friends

## Descripción

Existe un desconocimiento general en la industria sobre approval testings y el concepto de ˝golden master˝. Puede ser especialmente útil trabajando con código legacy o tus deberes de la uni.

- **Duración**: nos adaptamos a cualquier cosa. Un mínimo de 1 hora y un máximo de 3 sería razonable.
- **Mecánica**: breve chapa inicial, mucha práctica, bloques llamados ˝free-flowing˝… mucha discusión facilitada, intercambio de ideas… y buen ambiente.

## Nivel

> ¿Qué conocimientos sobre la materia se necesitan para acudir a la actividad? 

Todas las personas son bienvenidas, independientemente de su nivel. Habrá suficientes actividades preparadas como para manejar esto acordemente.

> ¿A qué audiencia estaría destinada?

A toda aquella que esté dispuesta a unirse :-)

## Información adicional

- Accesibilidad.
- Necesitamos internet, mesas y sillas. 1 flipchart y 1 proyector estaría de lujo, pero no son imprescindibles :)
- Sería interesante acudir con un ordenador en el que haya un entorno de desarrollo preparado (https://github.com/asturiashacking/practice-skeletons puede ayudar). ¿Dudas o problemas? Podemos abrir una issue en el repo y miramos a ver… sin fallo 👍 
- En muchos de nuestros eventos (extensible a empresas y aulas en la universidad) hay una amplia (y preocupante) mayoría de hombres blancos. ¿Qué podemos hacer para mejorar en este sentido? ¿Hablar más de estas cosas durante actividades? ¿Lenguaje inclusivo? ¿Y en las empresas / universidades?
- Como facilitador, uno de mis objetivos es garantizar espacios seguros donde todas las participantes se sientan cómodas, aka seguridad psicológica. Conveniente recordar que existe un código de conducta de la comunidad ;)

## Sobre mí

Me llamo Dani, y más allá de haber estado una hora para tratar de parsear un archivo de texto durante el último coding dojo, me gusta el desarrollo de software y aún más ver a gente motivada practicando, aprendiendo y sobre todo, compartiendo conocimiento.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Muchas gracias por la propuesta Dani! Genial para volver a tener una oportunidad de reunirnos a tirar unas líneas en comunidad

**Comment by dcarral** [comment]
@azaharafernandezguizan @sergioalvz Como ya hablamos alguna vez, por recientes conversaciones con folks como @jonatanmdez., @piedresybarro, @adelatorrefoss, etc. parece que hay sólido interés en disfrutar de coding dojos de forma periódica en la tierrina (aka no esperar meses desde proponer en este repositorio y celebrar la actividad, rotación de personas facilitando…). Siguiendo la línea de lo hecho por Toño @ Agile Asturias en su día vaya.

Si hacemos un esfuerzo pro-diversidad, inclusión, interseccionalidad podría quedar en algo bastante chulo, I guess.

¿Veis factible/interesante gestionar esto vía AsturiasHacking o mejor recurrir a alguna otra cosa? GDG Asturias? (:S), http://codingdojo.org/CodingDojos/, etc.

**Comment by Jonatanmdez** [comment]
> @azaharafernandezguizan @sergioalvz Como ya hablamos alguna vez, por recientes conversaciones con folks como @Jonatanmdez., @iquesada, @adelatorrefoss, etc. parece que hay sólido interés en disfrutar de coding dojos de forma periódica en la tierrina (aka no esperar meses desde proponer en este repositorio y celebrar la actividad, rotación de personas facilitando…). Siguiendo la línea de lo hecho por Toño @ Agile Asturias en su día.
> 
> Si hacemos un esfuerzo pro-diversidad, inclusión, interseccionalidad podría quedar en algo bastante chulo, I guess.
> 
> ¿Veis factible/interesante gestionar esto vía AsturiasHacking o mejor recurrir a alguna otra cosa? GDG Asturias? (:S), http://codingdojo.org/CodingDojos/, etc.

Creo que estaría bien incluso que fuera consecuente y siempre fuera el mismo día del mes, así como por ejemplo los eventos suelen ser (no siempre) el último jueves del mes, que los coding-dojo  estuvieran planificados con antelación, para que haya bastante habito y siempre tengamos uno al mes :)

**Comment by iquesada** [comment]
De semana, o de fin de semana? Cualquiera de las dos opciones tiene cosas buenas y cosas malas.
Personalmente prefiero de semana, pero habrá opiniones para todos los gustos.

**Comment by adelatorrefoss** [comment]
Me encantaría esa recurrencia . :)

**Comment by azaharafernandezguizan** [comment]
Hola gente, 
Voy a hablarlo con Sergio cuando vuelva y os decimos algo. Es una iniciativa muy interesante y que, como los que organizaba Toño, aporta mucho valor.

**Comment by SantiMA10** [comment]
Hola!
A mi también me mola la idea de tener coding dojos de forma periódica 🥳 y como seguro que os ha comentado @dcarral desde PrivacyCloud estaremos encantados de echar una mano con el espacio si hace falta 😋.

**Comment by sergioalvz** [comment]
Hola,

¿qué os parece si tenemos un hangouts para discutirlo?

Un saludo!

**Comment by dcarral** [comment]
:-)) ¿Quién lanza Doodle / Calendly / invite @ Google Calendar / alguna otra cosa?

**Comment by sergioalvz** [comment]
He hablado con @azaharafernandezguizan sobre ello y, entre que yo esta semana la tengo a full y que ella la semana que viene tiene también compromisos, sólo vemos viable el miércoles 29 a las 18:30, ¿qué os parece?

**Comment by adelatorrefoss** [comment]
Hola:
yo por mi bien.
A esa hora me pilla de camino a una clase, me podré conectar desde una
cafetería o similar.

Gracias!

**Comment by SantiMA10** [comment]
Por mi sin problema el miércoles

**Comment by Jonatanmdez** [comment]
Sin problemas por mi parte tampoco :)

**Comment by iquesada** [comment]
Perfect!

**Comment by sergioalvz** [comment]
Dejo aquí enlace para la llamada. Nos vemos el próximo miércoles!

https://meet.google.com/sox-cpmg-uha

**Comment by sergioalvz** [comment]
Compartimos meeting notes pronto. Gracias por asistir y echarnos una mano. We have a plan! 🙂🚀

**Comment by sergioalvz** [comment]
Con algo de retraso, pero ahí van las meeting notes.

***

### Participantes

- @azaharafernandezguizan 
- @adelatorrefoss 
- @Jonatanmdez 
- @iquesada 
- @SantiMA10 
- @sergioalvz 

- Los dojos serán organizados por un conjunto de voluntaries. Cada mes, le tocará a una persona hostear la actividad (buscar ubicación, facilitar la sesión, etc)
- Para facilitar las labores organizativas, vamos a utilizar una hoja de cálculo (solo accesible por la lista de voluntarias)
- Estas sesiones también podrán ser ocupadas por Dojos propuestos a través del mecanismo de Issues. En ese caso, la persona encargada de organizar la sesión se encargará únicamente de las labores logísticas.
- La comunicación de cada Dojo se realizará a través de Meetup

Actions items:

- @sergioalvz bootstrapping de hoja de cálculo, canal en Slack, configuración en Meetup (para que gente fuera de la organización pueda proponer eventos)
- @sergioalvz compartir con la comunidad como formar parte del grupo de voluntaries

**Comment by dcarral** [comment]
Como esta issue (en su forma original) creo que ya no aplica en este repo, y hay muchísimas abiertas… cerrando para aligerar un poco ;)
