### ISSUE TITLE
SOLID: An Introduction to the Solid project & Solid Search

### ISSUE THREAD

**Issue by alexcorvis84** [asturiashacking/activities#58]
# Propuesta de Actividad

## Título

SOLID: An Introduction to the Solid project & Solid Search

## Descripción

Charla introductoria sobre el proyecto [Solid](https://solidproject.org/) y la visión de un buscador para el comercio electrónico (e-commerce Solid Search) basado en su especificación y ecosistema, donde se pretende descentralizar los servicios de contextualización de búsqueda y dar un mayor control de la privacidad de los datos a los usuarios.

## Nivel

No se necesitan conocimientos previos, pero, para aquellas personas con conocimientos sobre Web Semántica y datos enlazados (Linked Data) puede que les resulte una gran oportunidad e interés conocer el proyecto.

## Información adicional

Conexión a Internet y proyector para presentar las slides de la charla. Con una hora, calculo que sería más que suficiente. Charla + Q&A

## Sobre mí

Mi nombre es Alejandro Juan García, y actualmente trabajo en Empathy.co como LABs Lead y Solid Search R&D PM. Me considero un entusiasta de la tecnología y siempre intento estar en continuo aprendizaje. Además, soy el actual presidente de la [Asociación Makers Asturias](http://makersasturias.com/), asociación sin ánimo de lucro en la que intentamos promover la cultura del 'Hazlo tu mismo' (DIY) y el movimiento Maker a través de distintos proyectos y tecnologías como puedan ser Internet de las Cosas, impresión 3D, electrónica, programación...

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola Alex,
Muchas gracias por la propuesta, nos encanta!. Estamos ahora mismo agendando las del primer trimestre de 2020, así que previsiblemente nos pondremos en contacto contigo para el segundo trimestre.

**Comment by azaharafernandezguizan** [comment]
Hola Alex, 
Como habrás visto, vamos a comenzar a unir en un meetup dos charlas, acortándolas un poco a 30 minutos para que sean más dinámicos y sacar mas provecho de cada uno. ¿Te viene bien este formato? ¿Que disponibilidad tendrías para impartir la charla en los próximos tres meses (Marzo, Abril y Mayo)? Vamos por orden de antigüedad y os estamos preguntando para tratar de cuadrar y agruparos de dos en dos :-)

**Comment by alexcorvis84** [comment]
Hola @azaharafernandezguizan ,

Sin problema con ese formato ;-)
En cuanto a disponibilidad, para los siguientes meses tanto Marzo/Abril/Mayo no tendría problema (en principio). Así que quedo al tanto de que me podáis dar una lista de posibles fechas y os pueda indicar cuál de ellas se me ajustaría mejor, ¿os parece? :-)

**Comment by azaharafernandezguizan** [comment]
Genial @alexcorvis84! ¿Podrías el miércoles 25 de Marzo que hay otro ponente que necesita darla ese día? Así os juntaríamos a los dos :-)

**Comment by alexcorvis84** [comment]
Hola @azaharafernandezguizan me parece buena fecha! Apuntado para el 25 de Marzo. Quedo pendiente de saber la hora ;) Entiendo que sea de tarde... Yo en principio, a partir de las 17.30 en adelante podría ;-)

**Comment by azaharafernandezguizan** [comment]
Hola @alexcorvis84  voy a reservar sitio y en cuanto lo tenga creo el meetup y te incluyo ¿me puedes pasar tu usuario de meetup por aquí o si quieres buscarme y enviármelo por meetup para que sea mas privado?
Saludos

**Comment by azaharafernandezguizan** [comment]
Hola @alexcorvis84 por problemas de espacio ¿podríamos cambiarla al jueves 26 de Marzo?

**Comment by alexcorvis84** [comment]
Como comentamos, quedamos para realizar la sesión el día 19 de Marzo en la Antigua Escuela de Comercio. Cualquier aviso, ya sabes dónde comunicarte conmigo :) ¡Gracias!

**Comment by azaharafernandezguizan** [comment]
Hola @alexcorvis84 , el tema del coronavirus hizo que estos últimos meses no hayamos podido realizar meetups presenciales. El mes que viene es el último antes del parón veraniego, y vamos a aprovechar el verano para organizar el próximo trimestre.

Como ya hace mucho tiempo que se propusiste esta actividad, nos gustaría saber si sigues interesado en impartirla en otoño, si no es así puedes cerrarla o por ausencia de respuesta la cerraré yo en unos días. 

Gracias por todo!

**Comment by alexcorvis84** [comment]
Hola Azahara!

Primero de todo disculpas por no haber contestado antes, con toda la
situación por la que hemos pasado, se me había pasado totalmente.

Por favor cuenta con mi asistencia para cuando os venga mejor, sin problema
me amoldo!

Estamos en contacto para lo que necesites y agendar dicha charla.

Un saludo 😉

**Comment by azaharafernandezguizan** [comment]
Hola, @alexcorvis84 estamos empezando a planear con tiempo las charlas de los próximos meses, ¿podríamos enviarnos un mail a asturiashacking@gmail.com para seguir con el proceso de buscarle fecha? 
Gracias!

**Comment by azaharafernandezguizan** [comment]
Hola @alexcorvis84, si sigues interesado en impartir esta propuesta escríbenos un correo a asturiashacking@gmail.com, sino en unos días cerraremos la propuesta :-)
