### ISSUE TITLE
Entendiendo RSA & ECC

### ISSUE THREAD

**Issue by m1guelpf** [asturiashacking/activities#59]
# Propuesta de Actividad

## Título

Entendiendo RSA & ECC

## Descripción

Inspirado un poco por #56, para la exploración matemática que he tenido que hacer para el IB elegí como tema los sistemas de criptografía RSA y ECC (criptografía de curva elíptica) y como resultado creo que he adquirido el conocimiento suficiente como para poder explicar como funcionan y por qué son seguros estos dos sistemas. Lo "dejo ahí" por si alguien está interesado.

## Nivel

Destinada a cualquiera que tenga interés en ella realmente. El único requisito sería haber atendido un poco en clase de matemáticas en 4ºESO / 2ºBUP / lo que sea.

## Información adicional

El único requisito sería un proyector para las diapositivas.

## Sobre mí

👋 Soy aquel adolescente que asistió a dos meetings y luego desapareció y no ha vuelto a asistir desde entonces 😅 Cursando 2º de [BI](https://ibo.org/es/programmes/diploma-programme/) y estoy construyendo [Sitesauce](https://sitesauce.app) en mi tiempo libre.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola Miguel!
Estamos ya con las propuestas para el segundo trimestre, así que previsiblemente te contactaremos para el tercer trimestre (sí, como en los cursos escolares). Nos alegra un montón que te apetezca compartir con nosotras y nosotros!!

**Comment by dcarral** [comment]
> Hola Miguel!
> Estamos ya con las propuestas para el segundo trimestre, así que previsiblemente te contactaremos **para el tercer trimestre** (sí, como en los cursos escolares). Nos alegra un montón que te apetezca compartir con nosotras y nosotros!!

¿¿Tercer trimestre?? Esto se nos está yendo de las manos… jajaja. ¿Habrá que pensar en agrupar varias charlas en un mismo evento como se hace por ahí en otras comunidades? (p.ej: http://up.front.ug/archive/ , https://www.rug-b.de/events/december-meetup-2019-575  ) ¿Alguna otra alternativa/idea? (p.ej: AsturiasHacking bis xD)

**Comment by azaharafernandezguizan** [comment]
Hola @m1guelpf ,
Como habrás visto, vamos a comenzar a unir en un meetup dos charlas, acortándolas un poco a 30 minutos para que sean más dinámicos y sacar mas provecho de cada uno. ¿Te viene bien este formato? ¿Que disponibilidad tendrías para impartir la charla en los próximos tres meses (Marzo, Abril y Mayo)? Vamos por orden de antigüedad y os estamos preguntando para tratar de cuadrar y agruparos de dos en dos :-)

**Comment by azaharafernandezguizan** [comment]
Hola @m1guelpf   estamos planeando las actividades de los próximos meses, ¿tienes disponibilidad a partir de Abril?

**Comment by azaharafernandezguizan** [comment]
Hola @m1guelpf  ,

¿Qué tal todo? Espero que dentro de la situación actual te encuentres bien y que tanto tú como tu familia tengáis buena salud.

Te escribo porque estamos pensando en retomar las sesiones de AsturiasHacking online pero de una forma diferente. Hemos pensado en mantener nuestra esencia y por ello, las sesiones serán online pero no se grabarán, tendrán un número limitado de participantes y además buscamos charlas cortas de 20-30 minutos para después tener un tiempo de networking. 

Nos preguntábamos si tu propuesta sigue en pie y si con estas condiciones te interesaría que la programásemos en los próximos meses.

Un saludo,
Azahara

**Comment by azaharafernandezguizan** [comment]
Hola @m1guelpf  , el tema del coronavirus hizo que estos últimos meses no hayamos podido realizar meetups presenciales. El mes que viene es el último antes del parón veraniego, y vamos a aprovechar el verano para organizar el próximo trimestre.

Como ya hace mucho tiempo que se propusiste esta actividad, nos gustaría saber si sigues interesado en impartirla en otoño, si no es así puedes cerrarla o por ausencia de respuesta la cerraré yo en unos días. 

Gracias por todo!
