### ISSUE TITLE
WeCodeFest 2020

### ISSUE THREAD

**Issue by Jonatanmdez** [asturiashacking/activities#62]
# Propuesta de Actividad

## WeCodeFest

 El fin de semana del 7 y 8 de Febrero se realiza en Valladolid el [`WeCodeFest 2020`](https://wecodefest.com/).

## Descripción
 El objetivo de la actividad es animar a todo el mundo que quiera ir, pero no se atreva porque piense que va a estar solo.

La idea es hacer una lista con las personas que van a ir (creo que va a ser una buena invasión asturiana) y ya organizarnos por privado el tema de compartir coche etc :) .

Es sobre todo animar a alguien que tenga dudas y nunca haya ido a un evento nacional a venir :) 

## Personas confirmadas para WeCodeFest 2020

1. @fontecha 
2. @jonatanmdez
3. @iquesada
4. @dcarral 

## Nivel

Al ser un evento muy practico, creo que si que es necesario tener algo de experiencia para sacar el valor a todo lo que se puede aprender en el evento. 

## Información adicional
El evento incluye cena viernes y fiesta sabado (normalmente). Es una buena oportunidad para conocer gente de otras comunidades :).

Es necesario ademas llevar portatil, hay mucha practica :)

## Sobre mí

Me llamo Jonatan Menendez y trabajo en remoto como desarrollador Backend PHP. Me gustan los gatos y aportar a la comunidad.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by iquesada** [comment]
Yo también tengo mi entrada @Jonatanmdez

**Comment by dcarral** [comment]
Fwiw bastante gente del equipo de PrivacyCloud acudiremos (confirmed right now: Santi, Carmen & myself). Estamos pensando en aprovechar la noche libre del Viernes (cena de ponentes) para reservar mesa en un sitio chulo y compartir mantel con gente chula (como vosotres :P), who is in? ;)

**Comment by Jonatanmdez** [comment]
> Fwiw bastante gente del equipo de PrivacyCloud acudiremos (confirmed right now: Santi, Carmen & myself). Estamos pensando en aprovechar la noche libre del Viernes (cena de ponentes) para reservar mesa en un sitio chulo y compartir mantel con gente chula (como vosotres :P), who is in? ;)

Yo me apunto :)

**Comment by iquesada** [comment]
Yo también!

**Comment by iquesada** [comment]
Hay que ir pensando en pillar transporte y alojamiento. Mi idea era llegar el 6 a última hora y quedarme hasta el domingo 9. De ahí tiro para Madrid.

Alguien va a llevar coche, o vamos en tren / bus?
@dcarral cuántas personas venís de PrivacyCloud?
Alguien que ya tenga resuelto el tema del alojamiento?

**Comment by dcarral** [comment]
3 confirmadas (Carmen, Santi, Dani) de momento. Iremos en transporte público (o bicicleta :P). Sería muy top llegar el Jueves a tiempo para un pinchoteo que habrá… tema alojamiento aún sin gestionar por nuestro lado. 

Looking so much forward! :-)

P.S.: Os doy acceso a una página de Notion donde se está mirando el tema nice Friday evening y demás ;)

**Comment by Jonatanmdez** [comment]
- Transporte: Nuestro idea (voy con @fontecha) es ir en tren. Como ofrecen descuento y tenemos el hotel al lado de la estación, win-win
- Hotel:  https://www.eleenaraboutiquehotel.com/ . Esta al lado de la estación
- Fechas: Nosotros llegaremos el jueves y nos quedamos hasta el domingo

**Comment by fontecha** [comment]
> Fwiw bastante gente del equipo de PrivacyCloud acudiremos (confirmed right now: Santi, Carmen & myself). Estamos pensando en aprovechar la noche libre del Viernes (cena de ponentes) para reservar mesa en un sitio chulo y compartir mantel con gente chula (como vosotres :P), who is in? ;)

Me apunto también  ;-)

**Comment by azaharafernandezguizan** [comment]
Cómo ya ha sido el WeCode y sé que lo habéis pasado en grande, cierro el issue  :-).
