### ISSUE TITLE
Creación de Videojuegos con Unity

### ISSUE THREAD

**Issue by rcriesgo** [asturiashacking/activities#63]
# Propuesta de Actividad

## Título

> Creación de videojuegos con la plataforma Unity. 

## Descripción

> No tengo experiencia profesional en el campo de los videojuegos, pero es uno de los motivos por los que me llegué a convertir en desarrollador y creo que muchas veces es una de las disciplinas olvidadas, más desconocidas entre las personas que nos dedicamos al desarrollo del software. 

La idea sería presentar una de las plataformas más populares para la creación de videojuegos (Unity) y ver paso a paso como desarrollar un sencillo videojuego 2D de plataformas.

## Nivel

> Cualquier persona con interés en la creación de videojuegos. Los ejemplos se realizarán en C#, pero la programación a realizar será muy sencilla. Si sabes cualquier otro lenguaje de programación no tendrás problemas. 

Incluso si no sabes programar puede ser interesante. Ya que el 80% de la charla se desarrollará utilizando componentes standard del entorno. 

## Información adicional

> Necesitaría un proyector y quizás conexión a internet para enseñar algunos recursos en linea.

## Sobre mí

> ¿Sobre mi? Soy un apasionado del mundo del desarrollo desde mi primer ordenador de 8 bits y cargar mis programas con cintas de audio (eso dará una idea de cuantos años llevo en esto). He realizado labores de formación y desarrollo de software en diferentes empresas y diferentes tipos de tecnología, y en la actualidad trabajo como arquitecto de software en Guidewire, ayudando a implantar nuestros productos a clientes por europa, y en mis ratitos de viajes... aprendo Unity. 
---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola @rcriesgo ,

Mil gracias por la propuesta! Suena muy interesante. Estamos planificando las propuestas del primer trimestre de 2020 y empezaremos a agruparlas para impartir dos en cada sesión probablemente. Te contactaremos previsiblemente para a partir de Semana Santa. 
Un saludo,
Azahara

**Comment by rcriesgo** [comment]
Oido @azaharafernandezguizan . En cuanto tengas alguna fecha tentativa te agradecería que me lo indicases, más que nada por poder elegir una fecha que no me coincida con viaje de trabajo. 

De cara a solaparlo con otras actividades. Lo que tengo previsto comentar necesitaría de una hora u hora y media.

**Comment by sergioalvz** [comment]
Hola @rcriesgo! ¿Crees que sería posible ajustar la duración de la charla a  30 minutos? Es uno de los (pocos) requisitos que tenemos con el objetivo de poder hacer los eventos un poco más dinámicos e incluir diferentes contenidos (como ves, tenemos una lista ya bastante larga de propuestas 😄) .

¡Muchas gracias por animarte a proponerte este tema! Pinta muy bien 😉

**Comment by azaharafernandezguizan** [comment]
Hola @rcriesgo estamos planeando las actividades de los próximos meses, ¿tienes disponibilidad a partir de Abril para impartir la charla en el formato que te comentaba Sergio?

**Comment by rcriesgo** [comment]
Perdonar el retraso en contestar, no me habia llegado ninguna notificacion. 

30 minutos se me antoja un poco escaso, mas que nada porque hay ciercos conceptos sobre la plataforma Unity que convendria explicar antes ya que el enfoque de un proyecto es un poco diferente a lo que estamos acostumbrados. Por otro lado, tengo el "timekeeping" es un aspecto que he de mejorar... tiendo a enrollarme cuando hablo de lo que me gusta. 

Una hora podria ser un tiempo mas ajustadito.

**Comment by ladyHekate** [comment]
genial, yo soy desarrolladora de videojuegos especialmente en unity .. trabajo con zbrush, blender, autodesk maya, marvelous, autodesk inventor, illustrator, corel, photoshop/ apenas vengo a conocer la plataforma de github y estoy emocionada ya que puedo mantener todo en orden, estaré pendiente por alguna notificación.

**Comment by azaharafernandezguizan** [comment]
Hola @rcriesgo  estamos empezando a planear con tiempo las charlas de los próximos meses, ¿podríamos enviarnos un mail a asturiashacking@gmail.com para seguir con el proceso de buscarle fecha? 
Gracias!

**Comment by azaharafernandezguizan** [comment]
Hola @rcriesgo , si sigues interesado en impartir esta propuesta escríbenos un correo a asturiashacking@gmail.com, sino en unos días cerraremos la propuesta :-)
