### ISSUE TITLE
Bioinformática. En qué consiste y para qué se utiliza. 

### ISSUE THREAD

**Issue by carcarmor** [asturiashacking/activities#64]
# Propuesta de Actividad

## Título

> Bioinformática. En qué consiste y para qué se utiliza. 

## Descripción
> La Bioinformática se ha convertido desde hace unos años en una herramienta fundamental para el estudio y tratamiento de datos dentro de las ciencias de la vida. Su desarrollo ha permitido entre otras cosas crear modelos biológicos _in silico_, tratar la ingente cantidad de datos que se generan en los laboratorios y compararlos, crear bases de datos internacionales y analizar secuencias de ADN y proteínas. Su importancia ha dado lugar a que muchos profesionales se especialicen en esta disciplina y es una opción muy interesante (y también una salida laboral) para el alumnado con formación en Informática, Matemáticas u otros. Además, las herramientas informáticas utilizadas por los científicos son a día de hoy una de las estrategias que existen para combatir y reducir la necesidad de animales de experimentación. En esta actividad tipo charla se comentaría de forma sencilla y divulgativa qué es la Bioinformática y algunas de sus aplicaciones (y aportaciones al avance de la ciencia). Al final de esta se hablaría también de las opciones formativas que existen para aquellos estudiantes con interés en esta especialización (que másters hay en España y Europa, empresas en España que necesitan personal con este tipo de formación, etc.). La duración sería de 15-20 minutos aproximadamente más una sesión de preguntas posterior para aclara cualquier tipo de duda o comentar temas de interés. 

## Nivel

> La intención es que la charla sea de carácter divulgativo y muy sencillo, sin tecnicismos.

## Información adicional

> Sería necesario un proyector para poder llevar una presentación y si hubiera una pizarra sería genial. Conexión a Internet también sería de utilidad pero no indispensable.

## Sobre mí

> Hola! Me llamo Carlota y estoy estudiando Biotecnología en la Universidad de Oviedo. Estoy en el último curso y voy a hacer un TFG de Bioinformática. Un amigo me habló de esta iniciativa y me dijo que sería guay que hablase de la Bioinformática y me pareció muy interesante. Tengo muchas ganas de aprender de los demás y de compartir un poco lo que sé. 

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola Carlota, nos encanta tu propuesta! Te cuento como funcionamos, vamos buscando fecha y planeándolas por orden de inscripción y vamos a comenzar a tener dos sesiones por meetup. Así que te contactaremos previsiblemente para el segundo trimestre de este año. Te mantenemos informada! Y muchas gracias por la propuesta :-)

**Comment by carcarmor** [comment]
Genial, muchas gracias!! :)

**Comment by carcarmor** [comment]
Genial, muchas gracias a ti! :)

**Comment by sergioalvz** [comment]
@carcarmor me parece súper interesante, ¡gracias!

**Comment by azaharafernandezguizan** [comment]
Hola @carcarmor   estamos planeando las actividades de los próximos meses, ¿tienes disponibilidad a partir de Abril? Sería un formato de charla de 30 minutos porque estamos empezando a juntar dos actividades en un mismo meetup ¿qué te parece?

**Comment by carcarmor** [comment]
Hola @azaharafernandezguizan me parece genial el formato. A partir de Abril podría participar sin problema. En ese período las únicas fechas complicadas para mí serán la última semana de mayo y la primera de junio porque tengo la presentación del TFG en la Universidad y preveo que estaré bastante apurada. Cualquier otra fecha me cuadra bien.

**Comment by azaharafernandezguizan** [comment]
Genial @carcarmor en unos días te digo algo, en cuanto haya mas candidatos para esas fechas!

**Comment by carcarmor** [comment]
Genial @azaharafernandezguizan :)

**Comment by azaharafernandezguizan** [comment]
Hola @carcarmor  estamos planeando un meetup para el 25 de Marzo ¿podrías darla en ese meetup?

**Comment by carcarmor** [comment]
Hola @azaharafernandezguizan ese día concreto no me viene bien porque tengo prácticas de laboratorio mañana y tarde y la asistencia es obligatoria, la semana siguiente a la del 25 ya no tendría prácticas.

**Comment by azaharafernandezguizan** [comment]
No te preocupes, es que se nos ha caído un ponente, seguimos con el plan original @carcarmor y te contacto cuando planeemos el de Abril

**Comment by azaharafernandezguizan** [comment]
Hola @carcarmor ,

¿Qué tal todo? Espero que dentro de la situación actual te encuentres bien y que tanto tú como tu familia tengáis buena salud.

Te escribo porque estamos pensando en retomar las sesiones de AsturiasHacking online pero de una forma diferente. Hemos pensado en mantener nuestra esencia y por ello, las sesiones serán online pero no se grabarán, tendrán un número limitado de participantes y además buscamos charlas cortas de 20-30 minutos para después tener un tiempo de networking.

Nos preguntábamos si tu propuesta sigue en pie y si con estas condiciones te interesaría que la programásemos en los próximos meses.

Un saludo,
Azahara

**Comment by carcarmor** [comment]
Hola Azahara,

Me encuentro bien gracias, espero que tú también. Me gustaría participar
igualmente, si me puedes comentar un poco más sobre cómo sería.

Un saludo,
Carlota

**Comment by azaharafernandezguizan** [comment]
Pues mira @carcarmor, si te viene bien podríamos organizar un meetup a finales de mes. 

Nuestra idea para hacerlo online sería con alguna herramienta (estamos mirando opciones para ver si encontramos algo que sea más chulo que las típicas videoconferencias), crear una reunión online con un número limitado de asistentes.

La idea sería no grabarlo, ni subirlo posteriormente a Youtube, sino que se siguiese manteniendo ese ambiente cordial e íntimo de AsturiasHacking.

 En cuanto a horario sería por la tarde, un día entre semana, para que las personas asistentes se puedan unir una vez hayan terminado de trabajar y nos gustaría que la agenda fuese algo como:
1) Tu charla con una duración de 30 minutos.
2) Espacio de preguntas (5-10 minutos)
3) Un espacio para networking online, con charlas distendidas e interacción social.

¿Qué te parece? ¿Tienes disponibilidad para la semana del 18 al 22 o la del 25 al 29?

**Comment by carcarmor** [comment]
Hola Azahara!

Me parece genial, podría la semana del 25 al 29!

Un saludo,
Carlota

**Comment by azaharafernandezguizan** [comment]
Que bien!! Lo hablo con Sergio, el otro organizador y ya te decimos fijo el día y la hora. Si quieres @carcamor puedes escribirme via meetup o te paso mi correo para seguir concretando detalles.

**Comment by carcarmor** [comment]
Hola!

Si puedes pasarme tu correo genial!

Un saludo,
Carlota

**Comment by azaharafernandezguizan** [comment]
Mira @carcarmor, es azaharafernandezguizan@gmail.com.

Gracias y buen finde!!

**Comment by azaharafernandezguizan** [comment]
De nuevo, muchas gracias por la propuesta y la charla, estuvo fenomenal!
