### ISSUE TITLE
Elephant Carpaccio, a coding dojo with user-story focus

### ISSUE THREAD

**Issue by woochica** [asturiashacking/activities#65]
# Propuesta de Actividad

## Título

Elephant Carpaccio, a coding dojo with user-story focus

## Descripción

[Elephant Carpaccio](https://alistair.cockburn.us/wp-content/uploads/2018/02/Elephant-Carpaccio-exercise-instructions.pdf) is a coding session for software developer groups. It’s designed to **practice breaking user stories into very thin, vertical slices that can be delivered within the sprints.** The format allows groups of 2-3 people to work in parallel. They can use pair-programming and switch by sprints. There's no limitation on the technology, it's up to the individual teams to decide what they want to use.

Duration: 1.5-2 hours

## Nivel

At least one person should be confident in writing software. Junior engineers are welcome to team-up with more experienced ones, and even people with no programming knowledge can join and help formulate the user stories or present to the client.

## Información adicional

- There's one computer per team needed
- A projector is needed to enable the teams to showcase their work to the group in the end of the session
- I can only facilitate the session in English; I need someone provide Spanish translation for those who need it so that everyone feels included

## Sobre mí

Soy Gabor Torok. My professional backround is in full stack web development, engineering management and teaching programming. I came across Elephant Carpaccio while I conducted a software engineering training for career changers in Berlin. I found the tool very helpful for bringing people with different technical knowledge together and creating an environment in which they need to collaborate closely.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by sergioalvz** [comment]
@woochica this sounds awesome, Gabor! 

Thank you :-)

**Comment by azaharafernandezguizan** [comment]
Thanks Gabor, we would contact you to schedule it probably in some months (we are scheduling activities for March-April now) And what about your availability to come to Asturias?

**Comment by woochica** [comment]
> Thanks Gabor, we would contact you to schedule it probably in some months (we are scheduling activities for March-April now) And what about your availability to come to Asturias?

Hi @azaharafernandezguizan! I will be in Asturias by the end of February for sure. After that I'm not sure yet, as I'm currently looking for jobs (and a place to settle :).

**Comment by woochica** [comment]
@azaharafernandezguizan: thanks for the follow-up. The workshop format I proposed here was designed for on-site gatherings. I wouldn't recommend it for a remote session. If there's a chance to hold an on-site meetup in the autumn, I'd be still up for facilitating the workshop.

**Comment by azaharafernandezguizan** [comment]
Hi @woochica, 

Due to the current situation with coronavirus, we are going to continue with online meetings during a while. As you have said that you preferred an on-site workshop, I am going to close this issue.
If in a near future we come back to on-site events, you are welcome to reopen this issue.

Thanks in advance,
