### ISSUE TITLE
Chocolate (con churros) 

### ISSUE THREAD

**Issue by dcarral** [asturiashacking/activities#66]
#live @ Uniovi

¿Lo mueves, Redondo? ;)

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Hola @dcarral ¿nos puedes detallar algo más? Para saber como catalogarla y eso, jeje

**Comment by dcarral** [comment]
Buenas @azaharafernandezguizan, ¡me suena tu cara! :P 

Esto viene a raíz de una conversación en Twitter, hace unas semanas / unos meses, en la que estuvo involucrada bastante gente de la comunidad (pensaba que tú también). En su día creo recordar que hablamos de una especie de lean coffee (con chocolate (con churros)). Algo así, por ejemplo, creo que podría quedar muy chulo :)

P.S.: El motivo de haber abierto esta issue fue una conversación con @jose-r-lopez la semana pasada durante el EII Tech Fest 2020 en la Escuela de Ingeniería Informática de Oviedo. Creo que hubo algún problema técnico que hizo que se retrasase mi charla por lo que tuve que recortar contenido de la misma, pero me hubiera gustado haber aprovechado la oportunidad para invitar a estudiantes de la Uni. Supongo que nada que no se pueda arreglar contactando con @delegación_eii una vez tengamos fecha/hora/lugar, ¿no?

**Comment by azaharafernandezguizan** [comment]
Perfect! Era por dejarlo más detallado para cuando lleguemos a programarla tenerlo claro. Un saludo.
