### ISSUE TITLE
Creando una galería de fotos accesible y dinámica

### ISSUE THREAD

**Issue by jmrp81** [asturiashacking/activities#67]
# Propuesta de Actividad

## Título

Creando una galería de fotos accesible y dinámica

## Descripción

Hace un mes pensé que una buena idea para una web que tengo era crear una galería de fotos dinámica. ¿El problema?, quería que fuese accesible también. En esta charla os contaré como la conseguí hacer utilizando Azure Cognitive Sensitive, Google Translator y Angular 9.

## Nivel

Principiante, lo contaré paso a paso.

## Información adicional

No hace falta nada especial, salvo un proyector.

## Sobre mí

Soy Juan Manuel Rodríguez Pérez, desarrollador de Software en Sngular y también formo parte de Afaya. En mis tiempos libres me gusta jugar a videojuegos, probar nuevas tecnologías y frameworks y me encanta compartir con la comunidad.

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by sergioalvz** [comment]
¡Tiene muy buena pinta, Juanma!

**Comment by azaharafernandezguizan** [comment]
Una propuesta interesante, más adelante cuando te llegue el turno ya te contactaremos para agendar día y hora

**Comment by azaharafernandezguizan** [comment]
Hola @jmrp81 ,

Te escribo porque estamos pensando en retomar las sesiones de AsturiasHacking online pero de una forma diferente. Hemos pensado en mantener nuestra esencia y por ello, las sesiones serán online pero no se grabarán, tendrán un número limitado de participantes y además buscamos charlas cortas de 20-30 minutos para después tener un tiempo de networking.

Nos preguntábamos si tu propuesta sigue en pie y si con estas condiciones te interesaría que la programásemos en los próximos meses.

Un saludo,
Azahara

**Comment by jmrp81** [comment]
Hola team, la podéis programar para cuando veáis, lo único que en 20 o 30 minutos me dara tiempo solo a ver la APP (encargada de obtener las descripciones  para las imagenes) y no la parte web.
