### ISSUE TITLE
NextJS: Tu nuevo framework JavaScript favorito

### ISSUE THREAD

**Issue by sergioalvz** [asturiashacking/activities#68]
# Propuesta de Actividad

## Título

NextJS: Tu nuevo framework JavaScript favorito

## Descripción

Charla breve para introducir NextJS y hablar sobre sus posibilidades y casos de uso. ¿Últimos 15-20 minutos de live coding? ¡Últimos 15-20 minutos de live coding!

## Nivel

Cualquier persona que esté dentro del desarrollo web y tenga cierta exposición al ecosistema JavaScript (¡o tenga interés en ello!)

## Información adicional

Conexión a internet + Proyector es más que suficiente.

## Sobre mí

¡Poco que decir que no haya dicho ya en otras issues + eventos! Podéis ver más sobre mí en: https://codecoolture.com

---

Todas nuestras actividades están obligadas a respetar nuestro [código de conducta][code of conduct] y cumplir el conjunto de [términos y condiciones][terms].

[code of conduct]: https://github.com/asturiashacking/core/blob/master/coc/CODE_OF_CONDUCT.md
[terms]: https://github.com/asturiashacking/activities/blob/master/TERMS.md

**Comment by azaharafernandezguizan** [comment]
Creo que va a aportar mucho valor!! Cuando le llegue el turno hablamos :-)

**Comment by sergioalvz** [comment]
¡Pero esto qué es! ¿No hay trato preferente para la organización? 😉 

Gracias Azahara!
