### ISSUE TITLE
(Charla)  Programas que se entienden a sí mismos. Metaprogramación en el siglo XXI.

### ISSUE THREAD

**Issue by dgsuarez** [asturiashacking/activities#7]
# Propuesta de Actividad

## Título

Programas que se entienden a sí mismos. Metaprogramación en el siglo XXI.

## Descripción

Introspección, reflectividad, macros... Veremos como diferentes lenguajes usan
estas técnicas para ayudar a hacer nuestro código más conciso y expresivo (y lo
fácil que es también conseguir todo lo contrario).

## Nivel

Aunque no asumiremos conocimientos específicos de ningún lenguaje de ni de las
técnicas que vamos a ver, sí que esperamos un nivel medio de programación.

## Información adicional

Necesitaría proyector.

## Sobre mí

Más de estar en xterm que en otra cosa. Va para unos años en una relación no
exclusiva y sin formalizar con Ruby. CTO en Sweetspot Intelligence.

<https://github.com/dgsuarez/>
[@dg_suarez](https://twitter.com/dg_suarez)

**Comment by sergioalvz** [comment]
@dgsuarez ¿cuándo te encajaría poder impartirla, Diego? ¿Enero?

**Comment by dgsuarez** [comment]
Sí, segunda mitad de Enero idealmente.

**Comment by sergioalvz** [comment]
Tentativa: 25 de enero de 2018. cc: @dgsuarez
