### ISSUE TITLE
(Charlas cortas) La hora de la herramienta con AsturiasHacking

### ISSUE THREAD

**Issue by tasugo** [asturiashacking/activities#8]
# Propuesta de Actividad

## Título

La hora de la herramienta con AsturiasHacking

## Descripción

A raíz del último evento de AsturiasHacking, donde el pair programming nos hizo descubrir trucos de los demás de los que no teníamos ni idea, hemos pensado en una sesión de demos, a modo de charlas cortas, de nuestras herramientas favoritas para que todes podamos aprender y empezar a usar editores, plugins, scripts, etc. que puedan facilitarnos el trabajo diario.

## Nivel

Cualquiera que utilice un ordenador a diario podría aprender de las charlas cortas, aunque la idea es que se centren en herramientas relacionadas con la programación.

## Información adicional

Si vas a hablarnos sobre alguna herramienta, sería bueno que trajeras un ordenador con conexión HDMI o algún adaptador para el proyector.

Si solo vienes a escuchar, no hace falta que traigas nada :)

## Sobre mí

No aplica, las charlas las dará toda persona que quiera :)

**Comment by tasugo** [comment]
Una herramienta que yo podría mostrar es GitKraken, cliente GUI para git presente en todas las plataformas. ¿Lo veis interesante? :thinking:

**Comment by m1guelpf** [comment]
Yo podría presentar Visual Studio Code, un editor de código creado por Microsoft que ha remplazado tanto a Sublime como a Atom en mis proyectos.

**Comment by tasugo** [comment]
Otra herramienta de la que podría hablar: oh-my-zsh. Un framework para configurar todo lo relativo a zsh, que es un shell (equivalente a bash) para entornos UNIX. Es más interesante de lo que parece! :stuck_out_tongue_closed_eyes:

**Comment by tasugo** [comment]
Y otra más: i3. Un gestor de ventanas para entornos GNU/Linux que no se parece a nada que hayas usado antes, pero que bien configurado puede ser muy potente :)

**Comment by tasugo** [comment]
Por cierto, si cualquier persona quiere hablar de alguna de las herramientas que yo estoy proponiendo, por supuesto que cedo mi puesto, que soy organizador y estoy "acaparando el micro" :joy:

**Comment by tasugo** [comment]
Quizá podáis sacar alguna idea de aquí: https://blog.axosoft.com/top-developer-tools-2018

¡Animaos!

**Comment by sergioalvz** [comment]
Yo podría hablar MUY brevemente sobre Emmet. Una notación muy sencilla pero que ayuda escribir HTML de manera mucho más rápida.

**Comment by Jonatanmdez** [comment]
En mi caso, y aunque más que herramientas son servicios podría hablar sobre:

 * Integración continua con Gitlab (importante que nos suene docker)
 * Cuando los test fallan: Sentry (https://sentry.io/welcome/) Error Tracking Software
 * BrowserStack  (https://www.browserstack.com/) Como testear tu página en todos los dispositivos sin tener que instalar ni una sola maquina virtual en tu ordenador

**Comment by tasugo** [comment]
De lujo @Jonatanmdez !!

**Comment by dgsuarez** [comment]
Yo os puedo enseñar mi entorno de programación con vim, o para algo todavía más breve sobre alguna herramienta CLI no estándar, como ag (buscar archivos),jq (procesar json),o csvkit (procesar csv).

**Comment by ZeusPerez** [comment]
Yo puedo enseñar Postman, que es una aplicación bastante sencillita de usar y para la gente que use APIs y no la conozca le puede facilitar mucho la vida.

**Comment by tasugo** [comment]
@dgsuarez y algo sobre dotfiles? Breve explicación (por si alguien desconoce su utilidad) + gestión? Si te cuadra, eh? Me parece interesante :)

**Comment by ssanchezmarc** [comment]
@tasugo te robo la de oh-my-zsh!... si te parece bien claro ;)

**Comment by tasugo** [comment]
Faltaría más @ssanchezmarc ! Cuanta más gente hable, mejor para todos, y yo tengo más cosillas :dancer:

**Comment by dgsuarez** [comment]
@tasugo pues claro :)

**Comment by morvader** [comment]
A mi 10 minutos por herramienta se me hace algo escaso. Supongo que saldrán preguntas y dudas, además de tener que cambiar el conector del portatil etc..

Con la cantidad de propuestas que están saliendo no sería el momento de dividirlo en varias sesiones o de organizar una agenda?.

A mi me gustaría hablaros sobre Fiddler para el testing web.

**Comment by tasugo** [comment]
@morvader Sí, tenía pensado fijar una agenda hoy, por ser viernes, para que tengamos claro todos quién hablará de qué, y así poder preparar mínimamente la presentación.

La idea es que las charlas sean muy cortas, pero es intencionado. Tienen que ser overviews breves, que enseñen la utilidad básica y despierten el interés, pero sin llegar ir al detalle/profundidad.

Sí que había pensado limitar a 1 o 2 preguntas cortas tras cada charla, y dejar el resto para el final, donde podríamos hacer una mesa redonda o simplemente tomando un zumín irnos preguntando :smile: 

Si vemos que se nos va de las manos (creo que estamos en el límite, hay unas 9-10 propuestas, 90 minutos, que es lo que han durado otros eventos... Podemos hacer una votación/filtro previo... O incluso allí, a modo de lean coffee.

O podemos convocar una segunda iteración, que parece que esto tiene éxito! :dancer:

**Comment by tasugo** [comment]
Agenda
-----------
Lo primero: al 99% se hará en el Centro de Cultura Antiguo Instituto (Gijón). Lo digo por si a alguien le viene mal, o no puede venir, que lo sepamos desde ya.

Se me ocurre que la agenda podría ser la siguiente:

Emmet - @sergioalvz 
GitKraken - @tasugo
BrowserStack - @Jonatanmdez 
CI en GitLab - @Jonatanmdez 
Dotfiles - @dgsuarez
Vim - @dgsuarez
VSCode - @m1guelpf 
Oh-My-Zsh - @ssanchezmarc 
Postman - @ZeusPerez 
Fiddler - @morvader 

De momento el formato lo mantendría: 10 minutos de charla + máximo 2 preguntas que deberán ser MUY breves, tanto por parte de quien pregunta como de quien responde. Creo que con todo esto nos iríamos a las 2h, que basándonos en meetups pasados es lo que solemos estar como máximo.

He limitado a 2 por persona ya que vamos justitos de tiempo, y para las personas que se pasaban de 2 he elegido yo *provisionalmente* en base a lo que más me mola a mí (xD). Claro está que @dgsuarez y @Jonatanmdez tenéis la última palabra sobre las dos que queráis presentar.

Quizá si alguien falla o si corremos mucho/vamos bien de tiempo podamos meter alguna otra al final... O, como dijimos, quizá podamos hacer una segunda parte en la que entrarían los descartes.

Cuando podáis id confirmando en esta issue por si alguien no pudiera presentar lo suyo y tuviéramos que ir preparando a los reservas.

Saludos y buen finde! :smiley:

**Comment by tasugo** [comment]
Confirmado: Será en el Centro de Cultura Antiguo Instituto.

**Comment by Jonatanmdez** [comment]
Por mi sin problemas @tasugo , me parece bien las dos propuestas que comentas, visto el exito me huele que habra más oportunidades para más ideas :)

**Comment by m1guelpf** [comment]
@tasugo Es muy probable que yo no pueda ir, igual podría hacerlo en la segunda tanda...

**Comment by dgsuarez** [comment]
@tasugo adelante con ello :)

**Comment by ssanchezmarc** [comment]
@tasugo a falta de causar mayor...cuenta conmigo! ;-)

**Comment by dcarral** [comment]
Bua, esto tiene una pinta increíble. Recuerdo con nostalgia a @dgsuarez hacer “magia” con esas herramientas en la línea de comandos... muy top. Maravilloso ver tanta gente con ganas de compartir y tantas herramientas tan interesantes, ¡va a molar muchísimo! :-)

**Comment by jsfdez** [comment]
Si aún se puede proponer tema yo podría hablar de [QtCreator](https://www.qt.io/qt-features-libraries-apis-tools-and-ide/#ide)

**Comment by tasugo** [comment]
@jsfdez Gracias por la propuesta! Para esta vez ya no cuadró, pero como parece que habrá segunda parte, te apunto :smile:

**Comment by morvader** [comment]
Buenas,

Por mi parte, no creo que este jueves pueda asistir al meetup.  :(

Lo siento mucho, espero no perderme el siguiente!

**Comment by jsfdez** [comment]
Añado un par de cosas de las que puedo hablar:

AWM.
Gerrit + Git.

Pero ya tendrá que ser la próxima vez que venga a Asturias.

**Comment by tasugo** [comment]
Tomo nota, @jsfdez. Gracias!

**Comment by iquesada** [comment]
Yo estoy trasteando con [Portainer](https://github.com/portainer/portainer), un UI para Docker y podría contar algo sobre él ¿Os parece interesante?
